<?php
define("MEMBER_0001", "Please provide a valid value for your username");
define("MEMBER_0002", "Please provide a valid value for your password");
define("MEMBER_0003", "Please provide a valid value for your registrant");
define("MEMBER_0004", "Please provide a valid value for your organization");
define("MEMBER_0005", "Please provide a valid value for your street 1");
define("MEMBER_0006", "Please provide a valid value for your street 2");
define("MEMBER_0007", "Please provide a valid value for your street 3");
define("MEMBER_0008", "Please provide a valid value for your city");
define("MEMBER_0009", "Please provide a valid value for your province");
define("MEMBER_0010", "Please provide a valid value for your country");
define("MEMBER_0011", "Please provide a valid value for your postalcode");
define("MEMBER_0012", "Please provide a valid value for your telephone");
define("MEMBER_0013", "Please provide a valid value for your fax");
define("MEMBER_0014", "Please provide a valid value for your email");
define("MEMBER_0015", "Please provide a valid value for your message");
define("MEMBER_0016", "The member has already existed. Please select another user name to sign up");
define("MEMBER_0017", "Please provide a valid value for your New Password");
define("MEMBER_0018", "The two passwords should be the same");
define("MEMBER_0019", "Please provide a vaild value for your Old Password");
define("MEMBER_0020", "Member information has been successfully updated");
define("MEMBER_0021", "Please provide a valid value for your username");
define("MEMBER_0022", "Please provide a valid value for your password");
define("MEMBER_0023", "Login fail, please input correct username and password");
define("MEMBER_0024", "Login fail, the account has been locked");
define("MEMBER_0025", "An email with password has been sent to your email");
define("MEMBER_0026", "No member info has been found, please provide a valid information");
define("MEMBER_0027", "Please provide a valid value for your password again");
define("MEMBER_0028", "Your password");
define("MEMBER_0029", "Please provide a valid value for Credit card ID number");
define("MEMBER_0030", "Please provide a valid value for address");
define("MEMBER_0031", "Please provide a valid value for Credit card name");
define("MEMBER_0032", "Please provide a valid value for Credit card number");
define("MEMBER_0033", "Please provide a valid value for date");
define("MEMBER_0034", "Please provide a valid value for year");
define("MEMBER_0035", "Please provide a valid value for Name");
define("MEMBER_0036", ".us domains should be registered for at least 2 years");
define("MEMBER_0037", "Account does not have enough balance.");
define("MEMBER_0038", "Another account with that email address already exists.");


define("ADMIN_0001", "Please provide a valid username");
define("ADMIN_0002", "Please provide a valid type");
define("ADMIN_0003", "Please provide a valid amount");
define("ADMIN_0004", "Please provide a valid note");
define("ADMIN_0005", "The member does not exist");
define("ADMIN_0006", "Update account failed");
define("ADMIN_0007", "Update account successfully");
define("ADMIN_0008", "Please provide a valid value for Administrator Name");
define("ADMIN_0009", "Please provide a valid value for Administrator Department");
define("ADMIN_0010", "Please provide a valid value for Administrator Password");
define("ADMIN_0011", "The two passwords should be the same");
define("ADMIN_0012", "Add administrator successfully");
define("ADMIN_0013", "Cannot found the administrator");
define("ADMIN_0014", "You can not modify Super-administrator account");
define("ADMIN_0015", "Modify Administrator info successfully");
define("ADMIN_0016", "Delete administrator successfully");
define("ADMIN_0017", "Set Administrator tasks successfully");
define("ADMIN_0018", "Cannot find the member");
define("ADMIN_0019", "Start");
define("ADMIN_0020", "Stop");
define("ADMIN_0021", "Delete member successfully");
define("ADMIN_0022", "Cannot finnd the product");
define("ADMIN_0023", "Start domain successfully");
define("ADMIN_0024", "Stop domain successfully");
define("ADMIN_0025", "Please provide a valid primary dns");
define("ADMIN_0026", "Please provide a valid secondary dns");
define("ADMIN_0027", "Modify default DNS successfully");
define("ADMIN_0028", "Modify prices successfully");
define("ADMIN_0029", "Please provide a valid website skin");
define("ADMIN_0030", "Please provide a valid title");
define("ADMIN_0031", "Please provide a valid copyright");
define("ADMIN_0032", "Please provide a valid pagesize, the value should be between 1 and 50");
define("ADMIN_0033", "Please provide a valid system status");
define("ADMIN_0034", "Update system successfully");
define("ADMIN_0035", "Sorry, you have no access to process");
define("ADMIN_0036", "Please provide a valid reseller id");
define("ADMIN_0037", "Please provide a valid reseller password");
define("ADMIN_0038", "Please provide a valid server host");
define("ADMIN_0039", "Please provide a valid server port");
define("ADMIN_0040", "Product update failed");
define("ADMIN_0041", "The fields cannot be empty");
define("ADMIN_0042", "Successfully updated settings!");
define("ADMIN_0043", "Test email sent successfully.");
define("ADMIN_0044", "Testing email settings failed!");

define("DOMAIN_0001", "Please provide a valid value for your registrant");
define("DOMAIN_0002", "Please provide a valid value for organization of registrant");
define("DOMAIN_0003", "Please provide a valid value for address 1 of registrant");
define("DOMAIN_0004", "Please provide a valid value for address 2 of registrant");
define("DOMAIN_0005", "Please provide a valid value for address 3 of registrant");
define("DOMAIN_0006", "Please provide a valid value for city of registrant");
define("DOMAIN_0007", "Please provide a valid value for province of registrant");
define("DOMAIN_0008", "Please provide a valid value for country of registrant");
define("DOMAIN_0009", "Please provide a valid value for postal code of registrant");
define("DOMAIN_0010", "Please provide a valid value for telephone of registrant");
define("DOMAIN_0011", "Please provide a valid value for fax of registrant");
define("DOMAIN_0012", "Please provide a valid value for E-mail of registrant");
define("DOMAIN_0013", "Please provide a valid value for your administrator");
define("DOMAIN_0014", "Please provide a valid value for organization of registrant");
define("DOMAIN_0015", "Please provide a valid value for address 1 of registrant");
define("DOMAIN_0016", "Please provide a valid value for address 2 of registrant");
define("DOMAIN_0017", "Please provide a valid value for address 3 of registrant");
define("DOMAIN_0018", "Please provide a valid value for city of registrant");
define("DOMAIN_0019", "Please provide a valid value for province of registrant");
define("DOMAIN_0020", "Please provide a valid value for country of registrant");
define("DOMAIN_0021", "Please provide a valid value for postal code of registrant");
define("DOMAIN_0022", "Please provide a valid value for telephone of registrant");
define("DOMAIN_0023", "Please provide a valid value for fax of registrant");
define("DOMAIN_0024", "Please provide a valid value for E-mail of registrant");
define("DOMAIN_0025", "Please provide a valid value for your technical");
define("DOMAIN_0026", "Please provide a valid value for organization of technical");
define("DOMAIN_0027", "Please provide a valid value for address 1 of technical");
define("DOMAIN_0028", "Please provide a valid value for address 2 of technical");
define("DOMAIN_0029", "Please provide a valid value for address 3 of technical");
define("DOMAIN_0030", "Please provide a valid value for city of technical");
define("DOMAIN_0031", "Please provide a valid value for province of technical");
define("DOMAIN_0032", "Please provide a valid value for country of technical");
define("DOMAIN_0033", "Please provide a valid value for postal code of technical");
define("DOMAIN_0034", "Please provide a valid value for telephone of technical");
define("DOMAIN_0035", "Please provide a valid value for fax of technical");
define("DOMAIN_0036", "Please provide a valid value for E-mail of technical");
define("DOMAIN_0037", "Please provide a valid value for your billing");
define("DOMAIN_0038", "Please provide a valid value for organization of billing");
define("DOMAIN_0039", "Please provide a valid value for address 1 of billing");
define("DOMAIN_0040", "Please provide a valid value for address 2 of billing");
define("DOMAIN_0041", "Please provide a valid value for address 3 of billing");
define("DOMAIN_0042", "Please provide a valid value for city of billing");
define("DOMAIN_0043", "Please provide a valid value for province of billing");
define("DOMAIN_0044", "Please provide a valid value for country of billing");
define("DOMAIN_0045", "Please provide a valid value for postal code of billing");
define("DOMAIN_0046", "Please provide a valid value for telephone of billing");
define("DOMAIN_0047", "Please provide a valid value for fax of billing");
define("DOMAIN_0048", "Please provide a valid value for E-mail of billing");
define("DOMAIN_0049", "Please provide a valid value for registration year");
define("DOMAIN_0050", "Please provide a valid value for password");
define("DOMAIN_0051", "The two passwords should be the same");
define("DOMAIN_0052", "Please provide a valid value for dns1");
define("DOMAIN_0053", "Please provide a valid value for dns2");
define("DOMAIN_0054", "The two dns can't be the same");
define("DOMAIN_0055", "Your balance is not sufficient for domain registration.");
define("DOMAIN_0056", "Connect server fail");
define("DOMAIN_0057", "Login fail");
define("DOMAIN_0058", "Create contact fail");
define("DOMAIN_0059", "Register domain fail");
define("DOMAIN_0060", "Modify domain password fail");
define("DOMAIN_0061", "Modify domain contact fail");
define("DOMAIN_0062", "Successfully modified domain contact");
define("DOMAIN_0063", "Modify domain DNS fail");
define("DOMAIN_0064", "Successfully modified domain DNS");
define("DOMAIN_0065", "Please select a domain to delete");
define("DOMAIN_0066", "Please select a domain type to upgrade");
define("DOMAIN_0067", "The domain type has already existed in system");
define("DOMAIN_0068", "Please provide a valid value for your domain type");
define("DOMAIN_0069", "Please provide a valid value for your domain");
define("DOMAIN_0070", "The domain you provided can't be more than 63 characters");
define("DOMAIN_0071", "The domain you provided is not in the appropriate format");
define("DOMAIN_0072", "Delete domain fail");
define("DOMAIN_0073", "Delete domain successfully");
define("DOMAIN_0074", "Please provide a valid value for year");
define("DOMAIN_0075", "Your balance is not sufficient to renew domain");
define("DOMAIN_0076", "Please select a domain to renew");
define("DOMAIN_0077", "Renew domain fail");
define("DOMAIN_0078", "Renew domain successfully");

define("ALL_0001", "Find data error");
define("All_0002", "Network error");
define("All_0003", "Config file error");
define("ALL_0004", "Update data error");
define("ALL_0005", "Insert data error");
?>
