<?php
define("MEMBER_0001", "Please provide a valid value for your username");
define("MEMBER_0002", "Please provide a valid value for your password");
define("MEMBER_0003", "Please provide a valid value for your registrant");
define("MEMBER_0004", "Please provide a valid value for your organization");
define("MEMBER_0005", "Please provide a valid value for your street 1");
define("MEMBER_0006", "Please provide a valid value for your street 2");
define("MEMBER_0007", "Please provide a valid value for your street 3");
define("MEMBER_0008", "Please provide a valid value for your city");
define("MEMBER_0009", "Please provide a valid value for your province");
define("MEMBER_0010", "Please provide a valid value for your country");
define("MEMBER_0011", "Please provide a valid value for your postalcode");
define("MEMBER_0012", "Please provide a valid value for your telephone");
define("MEMBER_0013", "Please provide a valid value for your fax");
define("MEMBER_0014", "Please provide a valid value for your email");
define("MEMBER_0015", "Please provide a valid value for your message");
define("MEMBER_0016", "The member has already existed. Please select another user name to sign up");
define("MEMBER_0017", "Please provide a valid value for your New Password");
define("MEMBER_0018", "The two passwords should be the same");
define("MEMBER_0019", "Please provide a vaild value for your Old Password");
define("MEMBER_0020", "Member information has been successfully updated");
define("MEMBER_0021", "Please provide a valid value for your username");
define("MEMBER_0022", "Please provide a valid value for your password");
define("MEMBER_0023", "Login fail, please input correct username and password");
define("MEMBER_0024", "Login fail, the account has been locked");
define("MEMBER_0025", "An email with password has been sent to your email");
define("MEMBER_0026", "No member info has been found, please provide a valid information");
define("MEMBER_0027", "Please provide a valid value for your password again");
define("MEMBER_0028", "Your password");
define("MEMBER_0029", "Please provide a valid value for Credit card ID number");
define("MEMBER_0030", "Please provide a valid value for address");
define("MEMBER_0031", "Please provide a valid value for Credit card name");
define("MEMBER_0032", "Please provide a valid value for Credit card number");
define("MEMBER_0033", "Please provide a valid value for date");
define("MEMBER_0034", "Please provide a valid value for year");
define("MEMBER_0035", "Please provide a valid value for Name");
define("MEMBER_0036", ".us domains should be registered for at least 2 years");
define("MEMBER_0037", "Account does not have enough balance.");
define("MEMBER_0038", "Another account with that email address already exists.");


define("ADMIN_0001", "Please provide a valid username");
define("ADMIN_0002", "Please provide a valid type");
define("ADMIN_0003", "Please provide a valid amount");
define("ADMIN_0004", "Please provide a valid note");
define("ADMIN_0005", "The member does not exist");
define("ADMIN_0006", "Update account failed");
define("ADMIN_0007", "Update account successfully");
define("ADMIN_0008", "Please provide a valid value for Administrator Name");
define("ADMIN_0009", "Please provide a valid value for Administrator Department");
define("ADMIN_0010", "Please provide a valid value for Administrator Password");
define("ADMIN_0011", "The two passwords should be the same");
define("ADMIN_0012", "Add administrator successfully");
define("ADMIN_0013", "Cannot found the administrator");
define("ADMIN_0014", "You can not modify Super-administrator account");
define("ADMIN_0015", "Modify Administrator info successfully");
define("ADMIN_0016", "Delete administrator successfully");
define("ADMIN_0017", "Set Administrator tasks successfully");
define("ADMIN_0018", "Cannot find the member");
define("ADMIN_0019", "Start");
define("ADMIN_0020", "Stop");
define("ADMIN_0021", "Delete member successfully");
define("ADMIN_0022", "Cannot finnd the product");
define("ADMIN_0023", "Start domain successfully");
define("ADMIN_0024", "Stop domain successfully");
define("ADMIN_0025", "Please provide a valid primary dns");
define("ADMIN_0026", "Please provide a valid secondary dns");
define("ADMIN_0027", "Modify default DNS successfully");
define("ADMIN_0028", "Modify prices successfully");
define("ADMIN_0029", "Please provide a valid website skin");
define("ADMIN_0030", "Please provide a valid title");
define("ADMIN_0031", "Please provide a valid copyright");
define("ADMIN_0032", "Please provide a valid pagesize, the value should be between 1 and 50");
define("ADMIN_0033", "Please provide a valid system status");
define("ADMIN_0034", "Update system successfully");
define("ADMIN_0035", "Sorry, you have no access to process");
define("ADMIN_0036", "Please provide a valid reseller id");
define("ADMIN_0037", "Please provide a valid reseller password");
define("ADMIN_0038", "Please provide a valid server host");
define("ADMIN_0039", "Please provide a valid server port");
define("ADMIN_0040", "Product update failed");
define("ADMIN_0041", "The fields cannot be empty");
define("ADMIN_0042", "Successfully updated settings!");
define("ADMIN_0043", "Test email sent successfully.");
define("ADMIN_0044", "Testing email settings failed!");

define("DOMAIN_0001", "Please provide a valid value for your registrant");
define("DOMAIN_0002", "Please provide a valid value for organization of registrant");
define("DOMAIN_0003", "Please provide a valid value for address 1 of registrant");
define("DOMAIN_0004", "Please provide a valid value for address 2 of registrant");
define("DOMAIN_0005", "Please provide a valid value for address 3 of registrant");
define("DOMAIN_0006", "Please provide a valid value for city of registrant");
define("DOMAIN_0007", "Please provide a valid value for province of registrant");
define("DOMAIN_0008", "Please provide a valid value for country of registrant");
define("DOMAIN_0009", "Please provide a valid value for postal code of registrant");
define("DOMAIN_0010", "Please provide a valid value for telephone of registrant");
define("DOMAIN_0011", "Please provide a valid value for fax of registrant");
define("DOMAIN_0012", "Please provide a valid value for E-mail of registrant");
define("DOMAIN_0013", "Please provide a valid value for your administrator");
define("DOMAIN_0014", "Please provide a valid value for organization of registrant");
define("DOMAIN_0015", "Please provide a valid value for address 1 of registrant");
define("DOMAIN_0016", "Please provide a valid value for address 2 of registrant");
define("DOMAIN_0017", "Please provide a valid value for address 3 of registrant");
define("DOMAIN_0018", "Please provide a valid value for city of registrant");
define("DOMAIN_0019", "Please provide a valid value for province of registrant");
define("DOMAIN_0020", "Please provide a valid value for country of registrant");
define("DOMAIN_0021", "Please provide a valid value for postal code of registrant");
define("DOMAIN_0022", "Please provide a valid value for telephone of registrant");
define("DOMAIN_0023", "Please provide a valid value for fax of registrant");
define("DOMAIN_0024", "Please provide a valid value for E-mail of registrant");
define("DOMAIN_0025", "Please provide a valid value for your technical");
define("DOMAIN_0026", "Please provide a valid value for organization of technical");
define("DOMAIN_0027", "Please provide a valid value for address 1 of technical");
define("DOMAIN_0028", "Please provide a valid value for address 2 of technical");
define("DOMAIN_0029", "Please provide a valid value for address 3 of technical");
define("DOMAIN_0030", "Please provide a valid value for city of technical");
define("DOMAIN_0031", "Please provide a valid value for province of technical");
define("DOMAIN_0032", "Please provide a valid value for country of technical");
define("DOMAIN_0033", "Please provide a valid value for postal code of technical");
define("DOMAIN_0034", "Please provide a valid value for telephone of technical");
define("DOMAIN_0035", "Please provide a valid value for fax of technical");
define("DOMAIN_0036", "Please provide a valid value for E-mail of technical");
define("DOMAIN_0037", "Please provide a valid value for your billing");
define("DOMAIN_0038", "Please provide a valid value for organization of billing");
define("DOMAIN_0039", "Please provide a valid value for address 1 of billing");
define("DOMAIN_0040", "Please provide a valid value for address 2 of billing");
define("DOMAIN_0041", "Please provide a valid value for address 3 of billing");
define("DOMAIN_0042", "Please provide a valid value for city of billing");
define("DOMAIN_0043", "Please provide a valid value for province of billing");
define("DOMAIN_0044", "Please provide a valid value for country of billing");
define("DOMAIN_0045", "Please provide a valid value for postal code of billing");
define("DOMAIN_0046", "Please provide a valid value for telephone of billing");
define("DOMAIN_0047", "Please provide a valid value for fax of billing");
define("DOMAIN_0048", "Please provide a valid value for E-mail of billing");
define("DOMAIN_0049", "Please provide a valid value for registration year");
define("DOMAIN_0050", "Please provide a valid value for password");
define("DOMAIN_0051", "The two passwords should be the same");
define("DOMAIN_0052", "Please provide a valid value for dns1");
define("DOMAIN_0053", "Please provide a valid value for dns2");
define("DOMAIN_0054", "The two dns can't be the same");
define("DOMAIN_0055", "Your balance is not sufficient for domain registration.");
define("DOMAIN_0056", "Connect server fail");
define("DOMAIN_0057", "Login fail");
define("DOMAIN_0058", "Create contact fail");
define("DOMAIN_0059", "Register domain fail");
define("DOMAIN_0060", "Modify domain password fail");
define("DOMAIN_0061", "Modify domain contact fail");
define("DOMAIN_0062", "Successfully modified domain contact");
define("DOMAIN_0063", "Modify domain DNS fail");
define("DOMAIN_0064", "Successfully modified domain DNS");
define("DOMAIN_0065", "Please select a domain to delete");
define("DOMAIN_0066", "Please select a domain type to upgrade");
define("DOMAIN_0067", "The domain type has already existed in system");
define("DOMAIN_0068", "Please provide a valid value for your domain type");
define("DOMAIN_0069", "Please provide a valid value for your domain");
define("DOMAIN_0070", "The domain you provided can't be more than 63 characters");
define("DOMAIN_0071", "The domain you provided is not in the appropriate format");
define("DOMAIN_0072", "Delete domain fail");
define("DOMAIN_0073", "Delete domain successfully");
define("DOMAIN_0074", "Please provide a valid value for year");
define("DOMAIN_0075", "Your balance is not sufficient to renew domain");
define("DOMAIN_0076", "Please select a domain to renew");
define("DOMAIN_0077", "Renew domain fail");
define("DOMAIN_0078", "Renew domain successfully");

define("ALL_0001", "Find data error");
define("All_0002", "Network error");
define("All_0003", "Config file error");
define("ALL_0004", "Update data error");
define("ALL_0005", "Insert data error");
define("ALL_0006", "Captcha error");

define("WHOIS_0001", "Domain is available for registration.");
define("WHOIS_0002", "Domain is available for registration (premium).");
define("WHOIS_0003", "Domain is unavailable for registration.");
define("WHOIS_0004", "Domain availability could not be checked for registration.");
define("WHOIS_0005", "Unable to lookup whois information for domain.");
define("WHOIS_0006", "New query");

define("TEMPLATE_0001", 'Check result');
define("TEMPLATE_0002", 'Manage DNS');
define("TEMPLATE_0003", 'You can add new name servers or edit the existing nameservers.');
define("TEMPLATE_0004", 'Domain list');
define("TEMPLATE_0005", 'Welcome to Manage Domain Area!	You may adopt this tool to implement domain management, including domain renewal & deletion, domain information modification and nameserver change.');
define("TEMPLATE_0006", 'Secure Your Domains');
define("TEMPLATE_0007", '&nbsp; Domain locking prevents unwanted registrar transfers and DNS changes to the domain names');
define("TEMPLATE_0008", 'Domain Auto-Renewal Service');
define("TEMPLATE_0009", '&nbsp; Change the domain Auto-Renewal settings here');
define("TEMPLATE_0010", 'Domain whois sync');
define("TEMPLATE_0011", 'Please input the user name and the domain name');
define("TEMPLATE_0012", 'Domain whois sync result');
define("TEMPLATE_0013", 'Email Customization');
define("TEMPLATE_0014", '&nbsp; Please enter details of the email to be sent.');
define("TEMPLATE_0015", 'Email Notification Options');
define("TEMPLATE_0016", 'Funds Management');
define("TEMPLATE_0017", 'Modify member level');
define("TEMPLATE_0018", 'If you want to modify member level after funds activity, please reset it for this member in following panel. ');
define("TEMPLATE_0019", 'Administrator List &gt; Add Administrator');
define("TEMPLATE_0020", 'Administrator List &gt; Modify Administrator Info');
define("TEMPLATE_0021", 'Administrator List');
define("TEMPLATE_0022", "Are you sure to delete this Administrator?");
define("TEMPLATE_0023", 'Administrator List &gt; Access Setting');
define("TEMPLATE_0024", 'Member List');
define("TEMPLATE_0025", 'Member List &gt; Modify member information');
define("TEMPLATE_0026", 'Member List &gt; View member information');
define("TEMPLATE_0027", 'My Account');
define("TEMPLATE_0028", 'Edit DNS');
define("TEMPLATE_0029", '&nbsp;Enter the IP corresponding to the nameserver.');
define("TEMPLATE_0030", 'Payment Gateway info');
define("TEMPLATE_0031", '&nbsp;&nbsp; Please update the payment gateway details.');
define("TEMPLATE_0032", 'Domain Setting');
define("TEMPLATE_0033", 'Domain Setting &gt; Default DNS');
define("TEMPLATE_0034", 'Domain Setting &gt; Domain Pricing');
define("TEMPLATE_0035", 'Add domain type');
define("TEMPLATE_0036", 'Please enter the queries for adding the new domain type (Sample queries are shown below)');
define("TEMPLATE_0037", 'Domain upgrade');
define("TEMPLATE_0038", 'This section is used to add the new domain into your domain business scope. If you find any new domains below you are interested in, please feel free to choose them.');
define("TEMPLATE_0039", 'Domain upgrade result');
define("TEMPLATE_0040", 'Transaction History');
define("TEMPLATE_0041", 'Register domain');
define("TEMPLATE_0042", "Please input the correct registration information into the following form.");
define("TEMPLATE_0043", 'Register New DNS');
define("TEMPLATE_0044", '&nbsp;Enter the name server name and the IP');
define("TEMPLATE_0045", 'Modify domain DNS');
define("TEMPLATE_0046", 'Please input the valid nameserver in the following line.');
define("TEMPLATE_0047", 'Select username');
define("TEMPLATE_0048", "Please input user name, which you are going to register this domain for.");
define("TEMPLATE_0049", 'Select username');
define("TEMPLATE_0050", "Please input user name, which you are going to register this domain(s) for.");
define("TEMPLATE_0051", 'Super-admin area &gt; System Setting');
define("TEMPLATE_0052", 'Logout');
define("TEMPLATE_0053", 'Help');
define("TEMPLATE_0054", "Super-admin Area");
define("TEMPLATE_0055", 'Administrator List');
define("TEMPLATE_0056", 'System Setting');
define("TEMPLATE_0057", 'E-mail settings');
define("TEMPLATE_0058", 'Configure gateway');
define("TEMPLATE_0059", 'Product Management');
define("TEMPLATE_0060", 'Domain Setting');
define("TEMPLATE_0061", 'Domain Upgrade');
define("TEMPLATE_0062", 'Manage Domain');
define("TEMPLATE_0063", 'Manage DNS');
define("TEMPLATE_0064", 'Register Domain');
define("TEMPLATE_0065", 'Domain Sync');
define("TEMPLATE_0066", 'Domain Lock');
define("TEMPLATE_0067", 'Domain Autorenewal');
define("TEMPLATE_0068", 'Member Management');
define("TEMPLATE_0069", 'Member List');
define("TEMPLATE_0070", 'Account Management');
define("TEMPLATE_0071", 'Funds Management');
define("TEMPLATE_0072", 'Query Transaction');
define("TEMPLATE_0073", 'Whois Search');
define("TEMPLATE_0074", 'Register domains');
define("TEMPLATE_0075", 'Please select the number of years');
define("TEMPLATE_0076", 'Check domain');
define("TEMPLATE_0077", 'Please input your desired domain name to check its availability');
define("TEMPLATE_0078", 'Check domain');
define("TEMPLATE_0079", 'Please input your desired domain name to check its availability');
define("TEMPLATE_0080", 'Check result');
define("TEMPLATE_0081", 'Domain list');
define("TEMPLATE_0082", 'Welcome to Manage Domain Area! You may adopt this tool to implement domain management, including domain renewal & deletion, domain information modification and nameserver change.');
define("TEMPLATE_0083", 'Register domain');
define("TEMPLATE_0084", 'Please input the correct registration information into the following form.');
define("TEMPLATE_0085", 'Registration result');
define("TEMPLATE_0086", 'Check domain');
define("TEMPLATE_0087", 'Please input your desired domain name to check its availability');
define("TEMPLATE_0088", 'Search Result');
define("TEMPLATE_0089", '&nbsp; Please select the domains to be registered ');
define("TEMPLATE_0090", 'Modify domain contact');
define("TEMPLATE_0091", 'Please input the new contact information directly to replace the old one.');
define("TEMPLATE_0092", 'Modify domain DNS');
define("TEMPLATE_0093", 'Please input the valid nameserver in the following line.');
define("TEMPLATE_0094", 'Whois');
define("TEMPLATE_0095", 'Please input the domain name to search its whois information');
define("TEMPLATE_0096", 'Whois Result');
define("TEMPLATE_0097", 'Confirm Payment');
define("TEMPLATE_0098", '&nbsp;&nbsp; Proceed to make the payment.');
define("TEMPLATE_0099", 'Forgot password');
define("TEMPLATE_0100", 'Please input your correct username and E-mail address to retrieve the password. Once you complete inputting the correct information, an E-mail with your new password will be automatically sent to you.');
define("TEMPLATE_0101", 'Member login');
define("TEMPLATE_0102", 'Please input your username and password to login.');
define("TEMPLATE_0103", 'My Account');
define("TEMPLATE_0104", 'Order history');
define("TEMPLATE_0105", 'Billing info');
define("TEMPLATE_0106", '&nbsp;&nbsp; Please update the payment method and details.');
define("TEMPLATE_0107", 'Payment Result');
define("TEMPLATE_0108", '&nbsp;&nbsp; Results of payment made.');
define("TEMPLATE_0109", 'Manage Funds');
define("TEMPLATE_0110", '&nbsp;&nbsp; Add funds to your account.');
define("TEMPLATE_0111", 'Member login');
define("TEMPLATE_0112", 'Please input your username and password to login.');
define("TEMPLATE_0113", 'Sign Up');
define("TEMPLATE_0114", 'Welcome to become our member! The line with asterisk(*) should be filled out completely.');
define("TEMPLATE_0115", 'Sign Up Result');
define("TEMPLATE_0116", 'Update account information');
define("TEMPLATE_0117", 'Please input your new account information directly. If you want to change account password, please input the old one and then input the new one. If you do not want to change it, please leave password lines in blank.');
define("TEMPLATE_0118", "System Error");
define("TEMPLATE_0119", 'System homepage');
define("TEMPLATE_0120", "Welcome");
define("TEMPLATE_0121", '<p>- FREE MEMBERSHIP</p>'
.'<p>- PAY WITH PAYPAL, OR CREDIT CARD</p>'
.'<p>- NO FUNDS EXPIRY</p>'
.'<p>- ADD AS MUCH FUNDS AS YOU NEED</p>'
.'<p>- EASY and SIMPLE MANAGEMENT</p>');
define("TEMPLATE_0122", 'System status');
define("TEMPLATE_0123", "Sorry, the system is in the maintenance");
define("TEMPLATE_0124", 'Home');
define("TEMPLATE_0125", 'My Account');
define("TEMPLATE_0126", 'Logout');
define("TEMPLATE_0127", "Business Tools");
define("TEMPLATE_0128", 'Whois Search');
define("TEMPLATE_0129", 'Register Domain');
define("TEMPLATE_0130", 'Manage Domain');
define("TEMPLATE_0131", 'Member Tools');
define("TEMPLATE_0132", 'Modify Account Info');
define("TEMPLATE_0133", 'Forgot Password');
define("TEMPLATE_0134", 'Transaction History');
define("TEMPLATE_0135", 'Product Management');
define("TEMPLATE_0136", 'Manage DNS');
define("TEMPLATE_0137", 'Domain AutoRenewal');
define("TEMPLATE_0138", 'Domain Lock');
define("TEMPLATE_0139", 'Fund Management');
define("TEMPLATE_0140", 'Manage Funds');
define("TEMPLATE_0141", 'Member Login');
define("TEMPLATE_0142", 'Whois Search');
define("TEMPLATE_0143", 'Sign Up');
define("TEMPLATE_0144", 'Register Domain');
define("TEMPLATE_0145", 'Forgot Password');
define("TEMPLATE_0146", 'Login');
define("TEMPLATE_0147", 'Other operation');

// reserved for future use.
define("TEMPLATE_0148", '');
define("TEMPLATE_0149", '');
define("TEMPLATE_0150", '');
define("TEMPLATE_0151", '');
define("TEMPLATE_0152", '');
define("TEMPLATE_0153", '');
define("TEMPLATE_0154", '');
define("TEMPLATE_0155", '');
define("TEMPLATE_0156", '');
define("TEMPLATE_0157", '');
define("TEMPLATE_0158", '');
define("TEMPLATE_0159", '');
?>
