<?php
define("MEMBER_0001", "Bitte geben Sie einen gültigen Wert für Ihren Benutzernamen an");
define("MEMBER_0002", "Bitte geben Sie einen gültigen Wert für Ihr Passwort an");
define("MEMBER_0003", "Bitte geben Sie einen gültigen Wert für Ihren Registranten an");
define("MEMBER_0004", "Bitte geben Sie einen gültigen Wert für Ihre Organisation an");
define("MEMBER_0005", "Bitte geben Sie einen gültigen Wert für Ihre Straße 1 an");
define("MEMBER_0006", "Bitte geben Sie einen gültigen Wert für Ihre Straße 2 an");
define("MEMBER_0007", "Bitte geben Sie einen gültigen Wert für Ihre Straße 3 an");
define("MEMBER_0008", "Bitte geben Sie einen gültigen Wert für Ihre Stadt an");
define("MEMBER_0009", "Bitte geben Sie einen gültigen Wert für Ihr Bundesland/Ihre Provinz an");
define("MEMBER_0010", "Bitte geben Sie einen gültigen Wert für Ihr Land an");
define("MEMBER_0011", "Bitte geben Sie einen gültigen Wert für Ihre Postleitzahl an");
define("MEMBER_0012", "Bitte geben Sie einen gültigen Wert für Ihr Telefon an");
define("MEMBER_0013", "Bitte geben Sie einen gültigen Wert für Ihr Fax an");
define("MEMBER_0014", "Bitte geben Sie einen gültigen Wert für Ihre E-Mail-Adresse an");
define("MEMBER_0015", "Bitte geben Sie einen gültigen Wert für Ihre Nachricht an");
define("MEMBER_0016", "Dieses Mitglied existiert bereits. Bitte wählen Sie einen anderen Benutzernamen für die Registrierung");
define("MEMBER_0017", "Bitte geben Sie einen gültigen Wert für Ihr neues Passwort an");
define("MEMBER_0018", "Die beiden Passwörter müssen übereinstimmen");
define("MEMBER_0019", "Bitte geben Sie einen gültigen Wert für Ihr altes Passwort an");
define("MEMBER_0020", "Die Mitgliedsinformationen wurden erfolgreich aktualisiert");
define("MEMBER_0021", "Bitte geben Sie einen gültigen Wert für Ihren Benutzernamen an");
define("MEMBER_0022", "Bitte geben Sie einen gültigen Wert für Ihr Passwort an");
define("MEMBER_0023", "Anmeldung fehlgeschlagen, bitte geben Sie den richtigen Benutzernamen und das richtige Passwort ein");
define("MEMBER_0024", "Anmeldung fehlgeschlagen, das Konto wurde gesperrt");
define("MEMBER_0025", "Eine E-Mail mit dem Passwort wurde an Ihre E-Mail-Adresse gesendet");
define("MEMBER_0026", "Es wurden keine Mitgliedsinformationen gefunden, bitte geben Sie gültige Informationen an");
define("MEMBER_0027", "Bitte geben Sie erneut einen gültigen Wert für Ihr Passwort an");
define("MEMBER_0028", "Ihr Passwort");
define("MEMBER_0029", "Bitte geben Sie einen gültigen Wert für die Kreditkarten-ID-Nummer an");
define("MEMBER_0030", "Bitte geben Sie einen gültigen Wert für die Adresse an");
define("MEMBER_0031", "Bitte geben Sie einen gültigen Wert für den Kreditkartennamen an");
define("MEMBER_0032", "Bitte geben Sie einen gültigen Wert für die Kreditkartennummer an");
define("MEMBER_0033", "Bitte geben Sie einen gültigen Wert für das Datum an");
define("MEMBER_0034", "Bitte geben Sie einen gültigen Wert für das Jahr an");
define("MEMBER_0035", "Bitte geben Sie einen gültigen Wert für den Namen an");
define("MEMBER_0036", ".us-Domains müssen für mindestens 2 Jahre registriert werden");
define("MEMBER_0037", "Das Konto verfügt nicht über ausreichendes Guthaben.");
define("MEMBER_0038", "Ein anderes Konto mit dieser E-Mail-Adresse existiert bereits.");


define("ADMIN_0001", "Bitte geben Sie einen gültigen Benutzernamen an");
define("ADMIN_0002", "Bitte geben Sie einen gültigen Typ an");
define("ADMIN_0003", "Bitte geben Sie einen gültigen Betrag an");
define("ADMIN_0004", "Bitte geben Sie eine gültige Notiz an");
define("ADMIN_0005", "Das Mitglied existiert nicht");
define("ADMIN_0006", "Aktualisierung des Kontos fehlgeschlagen");
define("ADMIN_0007", "Konto erfolgreich aktualisiert");
define("ADMIN_0008", "Bitte geben Sie einen gültigen Wert für den Administratornamen an");
define("ADMIN_0009", "Bitte geben Sie einen gültigen Wert für die Administratorabteilung an");
define("ADMIN_0010", "Bitte geben Sie einen gültigen Wert für das Administratorpasswort an");
define("ADMIN_0011", "Die beiden Passwörter müssen übereinstimmen");
define("ADMIN_0012", "Administrator erfolgreich hinzugefügt");
define("ADMIN_0013", "Der Administrator konnte nicht gefunden werden");
define("ADMIN_0014", "Sie können das Superadministrator-Konto nicht ändern");
define("ADMIN_0015", "Administratorinformationen erfolgreich geändert");
define("ADMIN_0016", "Administrator erfolgreich gelöscht");
define("ADMIN_0017", "Administratoraufgaben erfolgreich festgelegt");
define("ADMIN_0018", "Das Mitglied konnte nicht gefunden werden");
define("ADMIN_0019", "Start");
define("ADMIN_0020", "Stopp");
define("ADMIN_0021", "Mitglied erfolgreich gelöscht");
define("ADMIN_0022", "Das Produkt konnte nicht gefunden werden");
define("ADMIN_0023", "Domain erfolgreich gestartet");
define("ADMIN_0024", "Domain erfolgreich gestoppt");
define("ADMIN_0025", "Bitte geben Sie einen gültigen primären DNS an");
define("ADMIN_0026", "Bitte geben Sie einen gültigen sekundären DNS an");
define("ADMIN_0027", "Standard-DNS erfolgreich geändert");
define("ADMIN_0028", "Preise erfolgreich geändert");
define("ADMIN_0029", "Bitte geben Sie ein gültiges Website-Design an");
define("ADMIN_0030", "Bitte geben Sie einen gültigen Titel an");
define("ADMIN_0031", "Bitte geben Sie ein gültiges Copyright an");
define("ADMIN_0032", "Bitte geben Sie eine gültige Seitengröße an; der Wert muss zwischen 1 und 50 liegen");
define("ADMIN_0033", "Bitte geben Sie einen gültigen Systemstatus an");
define("ADMIN_0034", "System erfolgreich aktualisiert");
define("ADMIN_0035", "Entschuldigung, Sie haben keinen Zugriff auf diesen Vorgang");
define("ADMIN_0036", "Bitte geben Sie eine gültige Reseller-ID an");
define("ADMIN_0037", "Bitte geben Sie ein gültiges Reseller-Passwort an");
define("ADMIN_0038", "Bitte geben Sie einen gültigen Server-Host an");
define("ADMIN_0039", "Bitte geben Sie einen gültigen Server-Port an");
define("ADMIN_0040", "Produktaktualisierung fehlgeschlagen");
define("ADMIN_0041", "Die Felder dürfen nicht leer sein");
define("ADMIN_0042", "Einstellungen erfolgreich aktualisiert!");
define("ADMIN_0043", "Test-E-Mail erfolgreich gesendet.");
define("ADMIN_0044", "Test der E-Mail-Einstellungen fehlgeschlagen!");

define("DOMAIN_0001", "Bitte geben Sie einen gültigen Wert für Ihren Registranten an");
define("DOMAIN_0002", "Bitte geben Sie einen gültigen Wert für die Organisation des Registranten an");
define("DOMAIN_0003", "Bitte geben Sie einen gültigen Wert für Adresse 1 des Registranten an");
define("DOMAIN_0004", "Bitte geben Sie einen gültigen Wert für Adresse 2 des Registranten an");
define("DOMAIN_0005", "Bitte geben Sie einen gültigen Wert für Adresse 3 des Registranten an");
define("DOMAIN_0006", "Bitte geben Sie einen gültigen Wert für die Stadt des Registranten an");
define("DOMAIN_0007", "Bitte geben Sie einen gültigen Wert für das Bundesland/die Provinz des Registranten an");
define("DOMAIN_0008", "Bitte geben Sie einen gültigen Wert für das Land des Registranten an");
define("DOMAIN_0009", "Bitte geben Sie einen gültigen Wert für die Postleitzahl des Registranten an");
define("DOMAIN_0010", "Bitte geben Sie einen gültigen Wert für das Telefon des Registranten an");
define("DOMAIN_0011", "Bitte geben Sie einen gültigen Wert für das Fax des Registranten an");
define("DOMAIN_0012", "Bitte geben Sie einen gültigen Wert für die E-Mail-Adresse des Registranten an");
define("DOMAIN_0013", "Bitte geben Sie einen gültigen Wert für Ihren Administrator an");
define("DOMAIN_0014", "Bitte geben Sie einen gültigen Wert für die Organisation des Registranten an");
define("DOMAIN_0015", "Bitte geben Sie einen gültigen Wert für Adresse 1 des Registranten an");
define("DOMAIN_0016", "Bitte geben Sie einen gültigen Wert für Adresse 2 des Registranten an");
define("DOMAIN_0017", "Bitte geben Sie einen gültigen Wert für Adresse 3 des Registranten an");
define("DOMAIN_0018", "Bitte geben Sie einen gültigen Wert für die Stadt des Registranten an");
define("DOMAIN_0019", "Bitte geben Sie einen gültigen Wert für das Bundesland/die Provinz des Registranten an");
define("DOMAIN_0020", "Bitte geben Sie einen gültigen Wert für das Land des Registranten an");
define("DOMAIN_0021", "Bitte geben Sie einen gültigen Wert für die Postleitzahl des Registranten an");
define("DOMAIN_0022", "Bitte geben Sie einen gültigen Wert für das Telefon des Registranten an");
define("DOMAIN_0023", "Bitte geben Sie einen gültigen Wert für das Fax des Registranten an");
define("DOMAIN_0024", "Bitte geben Sie einen gültigen Wert für die E-Mail-Adresse des Registranten an");
define("DOMAIN_0025", "Bitte geben Sie einen gültigen Wert für Ihren technischen Kontakt an");
define("DOMAIN_0026", "Bitte geben Sie einen gültigen Wert für die Organisation des technischen Kontakts an");
define("DOMAIN_0027", "Bitte geben Sie einen gültigen Wert für Adresse 1 des technischen Kontakts an");
define("DOMAIN_0028", "Bitte geben Sie einen gültigen Wert für Adresse 2 des technischen Kontakts an");
define("DOMAIN_0029", "Bitte geben Sie einen gültigen Wert für Adresse 3 des technischen Kontakts an");
define("DOMAIN_0030", "Bitte geben Sie einen gültigen Wert für die Stadt des technischen Kontakts an");
define("DOMAIN_0031", "Bitte geben Sie einen gültigen Wert für das Bundesland/die Provinz des technischen Kontakts an");
define("DOMAIN_0032", "Bitte geben Sie einen gültigen Wert für das Land des technischen Kontakts an");
define("DOMAIN_0033", "Bitte geben Sie einen gültigen Wert für die Postleitzahl des technischen Kontakts an");
define("DOMAIN_0034", "Bitte geben Sie einen gültigen Wert für das Telefon des technischen Kontakts an");
define("DOMAIN_0035", "Bitte geben Sie einen gültigen Wert für das Fax des technischen Kontakts an");
define("DOMAIN_0036", "Bitte geben Sie einen gültigen Wert für die E-Mail-Adresse des technischen Kontakts an");
define("DOMAIN_0037", "Bitte geben Sie einen gültigen Wert für Ihren Rechnungskontakt an");
define("DOMAIN_0038", "Bitte geben Sie einen gültigen Wert für die Organisation des Rechnungskontakts an");
define("DOMAIN_0039", "Bitte geben Sie einen gültigen Wert für Adresse 1 des Rechnungskontakts an");
define("DOMAIN_0040", "Bitte geben Sie einen gültigen Wert für Adresse 2 des Rechnungskontakts an");
define("DOMAIN_0041", "Bitte geben Sie einen gültigen Wert für Adresse 3 des Rechnungskontakts an");
define("DOMAIN_0042", "Bitte geben Sie einen gültigen Wert für die Stadt des Rechnungskontakts an");
define("DOMAIN_0043", "Bitte geben Sie einen gültigen Wert für das Bundesland/die Provinz des Rechnungskontakts an");
define("DOMAIN_0044", "Bitte geben Sie einen gültigen Wert für das Land des Rechnungskontakts an");
define("DOMAIN_0045", "Bitte geben Sie einen gültigen Wert für die Postleitzahl des Rechnungskontakts an");
define("DOMAIN_0046", "Bitte geben Sie einen gültigen Wert für das Telefon des Rechnungskontakts an");
define("DOMAIN_0047", "Bitte geben Sie einen gültigen Wert für das Fax des Rechnungskontakts an");
define("DOMAIN_0048", "Bitte geben Sie einen gültigen Wert für die E-Mail-Adresse des Rechnungskontakts an");
define("DOMAIN_0049", "Bitte geben Sie einen gültigen Wert für das Registrierungsjahr an");
define("DOMAIN_0050", "Bitte geben Sie einen gültigen Wert für das Passwort an");
define("DOMAIN_0051", "Die beiden Passwörter müssen übereinstimmen");
define("DOMAIN_0052", "Bitte geben Sie einen gültigen Wert für DNS1 an");
define("DOMAIN_0053", "Bitte geben Sie einen gültigen Wert für DNS2 an");
define("DOMAIN_0054", "Die beiden DNS-Einträge dürfen nicht identisch sein");
define("DOMAIN_0055", "Ihr Guthaben reicht für die Domainregistrierung nicht aus.");
define("DOMAIN_0056", "Verbindung zum Server fehlgeschlagen");
define("DOMAIN_0057", "Anmeldung fehlgeschlagen");
define("DOMAIN_0058", "Erstellung des Kontakts fehlgeschlagen");
define("DOMAIN_0059", "Domainregistrierung fehlgeschlagen");
define("DOMAIN_0060", "Änderung des Domainpassworts fehlgeschlagen");
define("DOMAIN_0061", "Änderung des Domainkontakts fehlgeschlagen");
define("DOMAIN_0062", "Domainkontakt erfolgreich geändert");
define("DOMAIN_0063", "Änderung des Domain-DNS fehlgeschlagen");
define("DOMAIN_0064", "Domain-DNS erfolgreich geändert");
define("DOMAIN_0065", "Bitte wählen Sie eine Domain zum Löschen aus");
define("DOMAIN_0066", "Bitte wählen Sie einen Domaintyp zum Upgrade aus");
define("DOMAIN_0067", "Der Domaintyp existiert bereits im System");
define("DOMAIN_0068", "Bitte geben Sie einen gültigen Wert für Ihren Domaintyp an");
define("DOMAIN_0069", "Bitte geben Sie einen gültigen Wert für Ihre Domain an");
define("DOMAIN_0070", "Die angegebene Domain darf nicht länger als 63 Zeichen sein");
define("DOMAIN_0071", "Die angegebene Domain hat nicht das richtige Format");
define("DOMAIN_0072", "Löschen der Domain fehlgeschlagen");
define("DOMAIN_0073", "Domain erfolgreich gelöscht");
define("DOMAIN_0074", "Bitte geben Sie einen gültigen Wert für das Jahr an");
define("DOMAIN_0075", "Ihr Guthaben reicht nicht aus, um die Domain zu verlängern");
define("DOMAIN_0076", "Bitte wählen Sie eine Domain zur Verlängerung aus");
define("DOMAIN_0077", "Domainverlängerung fehlgeschlagen");
define("DOMAIN_0078", "Domain erfolgreich verlängert");

define("ALL_0001", "Fehler beim Suchen der Daten");
define("All_0002", "Netzwerkfehler");
define("All_0003", "Fehler in der Konfigurationsdatei");
define("ALL_0004", "Fehler beim Aktualisieren der Daten");
define("ALL_0005", "Fehler beim Einfügen der Daten");
define("ALL_0006", "Captcha-Fehler");

define("WHOIS_0001", "Domain ist zur Registrierung verfügbar.");
define("WHOIS_0002", "Domain ist zur Registrierung verfügbar (Premium).");
define("WHOIS_0003", "Domain ist nicht zur Registrierung verfügbar.");
define("WHOIS_0004", "Die Verfügbarkeit der Domain für die Registrierung konnte nicht geprüft werden.");
define("WHOIS_0005", "Whois-Informationen für die Domain konnten nicht abgefragt werden.");
define("WHOIS_0006", "Neue Abfrage");

define("TEMPLATE_0001", 'Prüfergebnis');
define("TEMPLATE_0002", 'DNS verwalten');
define("TEMPLATE_0003", 'Sie können neue Nameserver hinzufügen oder vorhandene Nameserver bearbeiten.');
define("TEMPLATE_0004", 'Domainliste');
define("TEMPLATE_0005", 'Willkommen im Domainverwaltungsbereich!	Sie können dieses Tool zur Domainverwaltung nutzen, einschließlich Domainverlängerung und -löschung, Änderung von Domaininformationen und Nameserverwechsel.');
define("TEMPLATE_0006", 'Sichern Sie Ihre Domains');
define("TEMPLATE_0007", '&nbsp; Die Domainsperre verhindert unerwünschte Registrar-Transfers und DNS-Änderungen an den Domainnamen');
define("TEMPLATE_0008", 'Dienst für automatische Domainverlängerung');
define("TEMPLATE_0009", '&nbsp; Ändern Sie hier die Einstellungen für die automatische Domainverlängerung');
define("TEMPLATE_0010", 'Domain-Whois-Synchronisierung');
define("TEMPLATE_0011", 'Bitte geben Sie den Benutzernamen und den Domainnamen ein');
define("TEMPLATE_0012", 'Ergebnis der Domain-Whois-Synchronisierung');
define("TEMPLATE_0013", 'E-Mail-Anpassung');
define("TEMPLATE_0014", '&nbsp; Bitte geben Sie die Details der zu sendenden E-Mail ein.');
define("TEMPLATE_0015", 'Optionen für E-Mail-Benachrichtigungen');
define("TEMPLATE_0016", 'Guthabenverwaltung');
define("TEMPLATE_0017", 'Mitgliedsstufe ändern');
define("TEMPLATE_0018", 'Wenn Sie die Mitgliedsstufe nach einer Guthabenaktivität ändern möchten, setzen Sie sie bitte im folgenden Bereich für dieses Mitglied zurück. ');
define("TEMPLATE_0019", 'Administratorliste &gt; Administrator hinzufügen');
define("TEMPLATE_0020", 'Administratorliste &gt; Administratorinformationen ändern');
define("TEMPLATE_0021", 'Administratorliste');
define("TEMPLATE_0022", "Sind Sie sicher, dass Sie diesen Administrator löschen möchten?");
define("TEMPLATE_0023", 'Administratorliste &gt; Zugriffseinstellungen');
define("TEMPLATE_0024", 'Mitgliederliste');
define("TEMPLATE_0025", 'Mitgliederliste &gt; Mitgliedsinformationen ändern');
define("TEMPLATE_0026", 'Mitgliederliste &gt; Mitgliedsinformationen anzeigen');
define("TEMPLATE_0027", 'Mein Konto');
define("TEMPLATE_0028", 'DNS bearbeiten');
define("TEMPLATE_0029", '&nbsp;Geben Sie die zum Nameserver gehörende IP-Adresse ein.');
define("TEMPLATE_0030", 'Informationen zum Zahlungs-Gateway');
define("TEMPLATE_0031", '&nbsp;&nbsp; Bitte aktualisieren Sie die Details des Zahlungs-Gateways.');
define("TEMPLATE_0032", 'Domain-Einstellung');
define("TEMPLATE_0033", 'Domain-Einstellung &gt; Standard-DNS');
define("TEMPLATE_0034", 'Domain-Einstellung &gt; Domainpreise');
define("TEMPLATE_0035", 'Domaintyp hinzufügen');
define("TEMPLATE_0036", 'Bitte geben Sie die Abfragen zum Hinzufügen des neuen Domaintyps ein (Beispielabfragen werden unten angezeigt)');
define("TEMPLATE_0037", 'Domain-Upgrade');
define("TEMPLATE_0038", 'Dieser Abschnitt dient dazu, neue Domains zu Ihrem Domain-Geschäftsbereich hinzuzufügen. Wenn Sie unten neue Domains finden, die Sie interessieren, können Sie diese gerne auswählen.');
define("TEMPLATE_0039", 'Ergebnis des Domain-Upgrades');
define("TEMPLATE_0040", 'Transaktionsverlauf');
define("TEMPLATE_0041", 'Domain registrieren');
define("TEMPLATE_0042", "Bitte geben Sie die korrekten Registrierungsinformationen in das folgende Formular ein.");
define("TEMPLATE_0043", 'Neuen DNS registrieren');
define("TEMPLATE_0044", '&nbsp;Geben Sie den Nameserver-Namen und die IP-Adresse ein');
define("TEMPLATE_0045", 'Domain-DNS ändern');
define("TEMPLATE_0046", 'Bitte geben Sie in der folgenden Zeile einen gültigen Nameserver ein.');
define("TEMPLATE_0047", 'Benutzernamen auswählen');
define("TEMPLATE_0048", "Bitte geben Sie den Benutzernamen ein, für den Sie diese Domain registrieren möchten.");
define("TEMPLATE_0049", 'Benutzernamen auswählen');
define("TEMPLATE_0050", "Bitte geben Sie den Benutzernamen ein, für den Sie diese Domain(s) registrieren möchten.");
define("TEMPLATE_0051", 'Superadmin-Bereich &gt; Systemeinstellung');
define("TEMPLATE_0052", 'Abmelden');
define("TEMPLATE_0053", 'Hilfe');
define("TEMPLATE_0054", "Superadmin-Bereich");
define("TEMPLATE_0055", 'Administratorliste');
define("TEMPLATE_0056", 'Systemeinstellung');
define("TEMPLATE_0057", 'E-Mail-Einstellungen');
define("TEMPLATE_0058", 'Gateway konfigurieren');
define("TEMPLATE_0059", 'Produktverwaltung');
define("TEMPLATE_0060", 'Domain-Einstellung');
define("TEMPLATE_0061", 'Domain-Upgrade');
define("TEMPLATE_0062", 'Domain verwalten');
define("TEMPLATE_0063", 'DNS verwalten');
define("TEMPLATE_0064", 'Domain registrieren');
define("TEMPLATE_0065", 'Domain-Synchronisierung');
define("TEMPLATE_0066", 'Domainsperre');
define("TEMPLATE_0067", 'Automatische Domainverlängerung');
define("TEMPLATE_0068", 'Mitgliederverwaltung');
define("TEMPLATE_0069", 'Mitgliederliste');
define("TEMPLATE_0070", 'Kontoverwaltung');
define("TEMPLATE_0071", 'Guthabenverwaltung');
define("TEMPLATE_0072", 'Transaktion abfragen');
define("TEMPLATE_0073", 'Whois-Suche');
define("TEMPLATE_0074", 'Domains registrieren');
define("TEMPLATE_0075", 'Bitte wählen Sie die Anzahl der Jahre aus');
define("TEMPLATE_0076", 'Domain prüfen');
define("TEMPLATE_0077", 'Bitte geben Sie Ihren gewünschten Domainnamen ein, um dessen Verfügbarkeit zu prüfen');
define("TEMPLATE_0078", 'Domain prüfen');
define("TEMPLATE_0079", 'Bitte geben Sie Ihren gewünschten Domainnamen ein, um dessen Verfügbarkeit zu prüfen');
define("TEMPLATE_0080", 'Prüfergebnis');
define("TEMPLATE_0081", 'Domainliste');
define("TEMPLATE_0082", 'Willkommen im Domainverwaltungsbereich! Sie können dieses Tool zur Domainverwaltung nutzen, einschließlich Domainverlängerung und -löschung, Änderung von Domaininformationen und Nameserverwechsel.');
define("TEMPLATE_0083", 'Domain registrieren');
define("TEMPLATE_0084", 'Bitte geben Sie die korrekten Registrierungsinformationen in das folgende Formular ein.');
define("TEMPLATE_0085", 'Registrierungsergebnis');
define("TEMPLATE_0086", 'Domain prüfen');
define("TEMPLATE_0087", 'Bitte geben Sie Ihren gewünschten Domainnamen ein, um dessen Verfügbarkeit zu prüfen');
define("TEMPLATE_0088", 'Suchergebnis');
define("TEMPLATE_0089", '&nbsp; Bitte wählen Sie die zu registrierenden Domains aus ');
define("TEMPLATE_0090", 'Domainkontakt ändern');
define("TEMPLATE_0091", 'Bitte geben Sie die neuen Kontaktinformationen direkt ein, um die alten zu ersetzen.');
define("TEMPLATE_0092", 'Domain-DNS ändern');
define("TEMPLATE_0093", 'Bitte geben Sie in der folgenden Zeile einen gültigen Nameserver ein.');
define("TEMPLATE_0094", 'Whois');
define("TEMPLATE_0095", 'Bitte geben Sie den Domainnamen ein, um dessen Whois-Informationen zu suchen');
define("TEMPLATE_0096", 'Whois-Ergebnis');
define("TEMPLATE_0097", 'Zahlung bestätigen');
define("TEMPLATE_0098", '&nbsp;&nbsp; Fahren Sie fort, um die Zahlung vorzunehmen.');
define("TEMPLATE_0099", 'Passwort vergessen');
define("TEMPLATE_0100", 'Bitte geben Sie Ihren korrekten Benutzernamen und Ihre E-Mail-Adresse ein, um das Passwort wiederherzustellen. Sobald Sie die korrekten Informationen vollständig eingegeben haben, wird Ihnen automatisch eine E-Mail mit Ihrem neuen Passwort zugesendet.');
define("TEMPLATE_0101", 'Mitgliederanmeldung');
define("TEMPLATE_0102", 'Bitte geben Sie Ihren Benutzernamen und Ihr Passwort ein, um sich anzumelden.');
define("TEMPLATE_0103", 'Mein Konto');
define("TEMPLATE_0104", 'Bestellverlauf');
define("TEMPLATE_0105", 'Rechnungsinformationen');
define("TEMPLATE_0106", '&nbsp;&nbsp; Bitte aktualisieren Sie die Zahlungsmethode und die Details.');
define("TEMPLATE_0107", 'Zahlungsergebnis');
define("TEMPLATE_0108", '&nbsp;&nbsp; Ergebnisse der geleisteten Zahlung.');
define("TEMPLATE_0109", 'Guthaben verwalten');
define("TEMPLATE_0110", '&nbsp;&nbsp; Fügen Sie Ihrem Konto Guthaben hinzu.');
define("TEMPLATE_0111", 'Mitgliederanmeldung');
define("TEMPLATE_0112", 'Bitte geben Sie Ihren Benutzernamen und Ihr Passwort ein, um sich anzumelden.');
define("TEMPLATE_0113", 'Registrieren');
define("TEMPLATE_0114", 'Willkommen als Mitglied! Die Zeile mit Sternchen (*) muss vollständig ausgefüllt werden.');
define("TEMPLATE_0115", 'Registrierungsergebnis');
define("TEMPLATE_0116", 'Kontoinformationen aktualisieren');
define("TEMPLATE_0117", 'Bitte geben Sie Ihre neuen Kontoinformationen direkt ein. Wenn Sie das Kontopasswort ändern möchten, geben Sie bitte zuerst das alte und anschließend das neue Passwort ein. Wenn Sie es nicht ändern möchten, lassen Sie die Passwortzeilen bitte leer.');
define("TEMPLATE_0118", "Systemfehler");
define("TEMPLATE_0119", 'System-Startseite');
define("TEMPLATE_0120", "Willkommen");
define("TEMPLATE_0121", '<p>- KOSTENLOSE MITGLIEDSCHAFT</p><p>- ZAHLUNG MIT PAYPAL ODER KREDITKARTE</p><p>- KEIN VERFALL DES GUTHABENS</p><p>- FÜGEN SIE SO VIEL GUTHABEN HINZU, WIE SIE BENÖTIGEN</p><p>- EINFACHE UND UNKOMPLIZIERTE VERWALTUNG</p>');
define("TEMPLATE_0122", 'Systemstatus');
define("TEMPLATE_0123", "Entschuldigung, das System befindet sich in Wartung");
define("TEMPLATE_0124", 'Startseite');
define("TEMPLATE_0125", 'Mein Konto');
define("TEMPLATE_0126", 'Abmelden');
define("TEMPLATE_0127", "Geschäftstools");
define("TEMPLATE_0128", 'Whois-Suche');
define("TEMPLATE_0129", 'Domain registrieren');
define("TEMPLATE_0130", 'Domain verwalten');
define("TEMPLATE_0131", 'Mitgliedertools');
define("TEMPLATE_0132", 'Kontoinformationen ändern');
define("TEMPLATE_0133", 'Passwort vergessen');
define("TEMPLATE_0134", 'Transaktionsverlauf');
define("TEMPLATE_0135", 'Produktverwaltung');
define("TEMPLATE_0136", 'DNS verwalten');
define("TEMPLATE_0137", 'Automatische Domainverlängerung');
define("TEMPLATE_0138", 'Domainsperre');
define("TEMPLATE_0139", 'Guthabenverwaltung');
define("TEMPLATE_0140", 'Guthaben verwalten');
define("TEMPLATE_0141", 'Mitgliederanmeldung');
define("TEMPLATE_0142", 'Whois-Suche');
define("TEMPLATE_0143", 'Registrieren');
define("TEMPLATE_0144", 'Domain registrieren');
define("TEMPLATE_0145", 'Passwort vergessen');
define("TEMPLATE_0146", 'Anmelden');
define("TEMPLATE_0147", 'Andere Operation');

define("TEMPLATE_LANG", 'Deutsch');
define("TEMPLATE_LANG_JS", "Bitte speichern Sie zuerst alle nicht gespeicherten Arbeiten oder Vorgänge.\n\nMöchten Sie die Seite jetzt neu laden?\n\nJa = Ich habe nichts Ungespeichertes, neu laden!\nNein = Ich speichere zuerst und lade später neu.");

// reserved for future use.
define("TEMPLATE_0148", '');
define("TEMPLATE_0149", '');
define("TEMPLATE_0150", '');
define("TEMPLATE_0151", '');
define("TEMPLATE_0152", '');
define("TEMPLATE_0153", '');
define("TEMPLATE_0154", '');
define("TEMPLATE_0155", '');
define("TEMPLATE_0156", '');
define("TEMPLATE_0157", '');
define("TEMPLATE_0158", '');
define("TEMPLATE_0159", '');
?>
