<?php
define("MEMBER_0001", "Lütfen geçerli bir kullanıcı adı giriniz");
define("MEMBER_0002", "Lütfen geçerli bir şifre giriniz");
define("MEMBER_0003", "Lütfen geçerli bir kayıt sahibi adı giriniz");
define("MEMBER_0004", "Lütfen geçerli bir kuruluş adı giriniz");
define("MEMBER_0005", "Lütfen geçerli bir 1. cadde adresi giriniz");
define("MEMBER_0006", "Lütfen geçerli bir 2. cadde adresi giriniz");
define("MEMBER_0007", "Lütfen geçerli bir 3. cadde adresi giriniz");
define("MEMBER_0008", "Lütfen geçerli bir şehir giriniz");
define("MEMBER_0009", "Lütfen geçerli bir il giriniz");
define("MEMBER_0010", "Lütfen geçerli bir ülke giriniz");
define("MEMBER_0011", "Lütfen geçerli bir posta kodu giriniz");
define("MEMBER_0012", "Lütfen geçerli bir telefon numarası giriniz");
define("MEMBER_0013", "Lütfen geçerli bir faks numarası giriniz");
define("MEMBER_0014", "Lütfen geçerli bir e-posta adresi giriniz");
define("MEMBER_0015", "Lütfen geçerli bir mesaj giriniz");
define("MEMBER_0016", "Bu kullanıcı zaten mevcut. Lütfen başka bir kullanıcı adı seçiniz");
define("MEMBER_0017", "Lütfen geçerli bir Yeni Şifre giriniz");
define("MEMBER_0018", "İki şifre aynı olmalıdır");
define("MEMBER_0019", "Lütfen geçerli bir Eski Şifre giriniz");
define("MEMBER_0020", "Üye bilgileri başarıyla güncellendi");
define("MEMBER_0021", "Lütfen geçerli bir kullanıcı adı giriniz");
define("MEMBER_0022", "Lütfen geçerli bir şifre giriniz");
define("MEMBER_0023", "Giriş başarısız, lütfen doğru kullanıcı adı ve şifre giriniz");
define("MEMBER_0024", "Giriş başarısız, hesap kilitlenmiş");
define("MEMBER_0025", "Şifrenizin bulunduğu bir e-posta adresinize gönderildi");
define("MEMBER_0026", "Üye bilgisi bulunamadı, lütfen geçerli bilgi giriniz");
define("MEMBER_0027", "Lütfen şifrenizi tekrar giriniz");
define("MEMBER_0028", "Şifreniz");
define("MEMBER_0029", "Lütfen geçerli bir kredi kartı ID numarası giriniz");
define("MEMBER_0030", "Lütfen geçerli bir adres giriniz");
define("MEMBER_0031", "Lütfen geçerli bir kredi kartı ismi giriniz");
define("MEMBER_0032", "Lütfen geçerli bir kredi kartı numarası giriniz");
define("MEMBER_0033", "Lütfen geçerli bir tarih giriniz");
define("MEMBER_0034", "Lütfen geçerli bir yıl giriniz");
define("MEMBER_0035", "Lütfen geçerli bir ad giriniz");
define("MEMBER_0036", ".us uzantılı alan adları en az 2 yıl kayıt edilmelidir");
define("MEMBER_0037", "Hesap bakiyesi yetersiz.");
define("MEMBER_0038", "Bu e-posta adresiyle kayıtlı başka bir hesap zaten var.");

define("ADMIN_0001", "Lütfen geçerli bir kullanıcı adı giriniz");
define("ADMIN_0002", "Lütfen geçerli bir tür giriniz");
define("ADMIN_0003", "Lütfen geçerli bir tutar giriniz");
define("ADMIN_0004", "Lütfen geçerli bir not giriniz");
define("ADMIN_0005", "Üye bulunamadı");
define("ADMIN_0006", "Hesap güncelleme başarısız");
define("ADMIN_0007", "Hesap başarıyla güncellendi");
define("ADMIN_0008", "Lütfen geçerli bir Yönetici Adı giriniz");
define("ADMIN_0009", "Lütfen geçerli bir Yönetici Departmanı giriniz");
define("ADMIN_0010", "Lütfen geçerli bir Yönetici Şifresi giriniz");
define("ADMIN_0011", "İki şifre aynı olmalıdır");
define("ADMIN_0012", "Yönetici başarıyla eklendi");
define("ADMIN_0013", "Yönetici bulunamadı");
define("ADMIN_0014", "Süper yönetici hesabı değiştirilemez");
define("ADMIN_0015", "Yönetici bilgisi başarıyla değiştirildi");
define("ADMIN_0016", "Yönetici başarıyla silindi");
define("ADMIN_0017", "Yönetici görevleri başarıyla atandı");
define("ADMIN_0018", "Üye bulunamadı");
define("ADMIN_0019", "Başlat");
define("ADMIN_0020", "Durdur");
define("ADMIN_0021", "Üye başarıyla silindi");
define("ADMIN_0022", "Ürün bulunamadı");
define("ADMIN_0023", "Alan adı başarıyla başlatıldı");
define("ADMIN_0024", "Alan adı başarıyla durduruldu");
define("ADMIN_0025", "Lütfen geçerli bir birincil DNS giriniz");
define("ADMIN_0026", "Lütfen geçerli bir ikincil DNS giriniz");
define("ADMIN_0027", "Varsayılan DNS başarıyla değiştirildi");
define("ADMIN_0028", "Fiyatlar başarıyla değiştirildi");
define("ADMIN_0029", "Lütfen geçerli bir site teması giriniz");
define("ADMIN_0030", "Lütfen geçerli bir başlık giriniz");
define("ADMIN_0031", "Lütfen geçerli bir telif hakkı bilgisi giriniz");
define("ADMIN_0032", "Lütfen geçerli bir sayfa boyutu giriniz, değer 1 ile 50 arasında olmalıdır");
define("ADMIN_0033", "Lütfen geçerli bir sistem durumu giriniz");
define("ADMIN_0034", "Sistem başarıyla güncellendi");
define("ADMIN_0035", "Üzgünüz, bu işlemi yapma yetkiniz yok");
define("ADMIN_0036", "Lütfen geçerli bir bayi ID giriniz");
define("ADMIN_0037", "Lütfen geçerli bir bayi şifresi giriniz");
define("ADMIN_0038", "Lütfen geçerli bir sunucu adı giriniz");
define("ADMIN_0039", "Lütfen geçerli bir sunucu portu giriniz");
define("ADMIN_0040", "Ürün güncelleme başarısız");
define("ADMIN_0041", "Alanlar boş bırakılamaz");
define("ADMIN_0042", "Ayarlar başarıyla güncellendi!");
define("ADMIN_0043", "Test e-postası başarıyla gönderildi.");
define("ADMIN_0044", "E-posta ayarları test edilemedi!");

define("DOMAIN_0001", "Lütfen geçerli bir kayıt sahibi adı giriniz");
define("DOMAIN_0002", "Lütfen geçerli bir kayıt sahibi kuruluşu giriniz");
define("DOMAIN_0003", "Lütfen geçerli bir kayıt sahibi adresi (1) giriniz");
define("DOMAIN_0004", "Lütfen geçerli bir kayıt sahibi adresi (2) giriniz");
define("DOMAIN_0005", "Lütfen geçerli bir kayıt sahibi adresi (3) giriniz");
define("DOMAIN_0006", "Lütfen kayıt sahibi için geçerli bir şehir giriniz");
define("DOMAIN_0007", "Lütfen kayıt sahibi için geçerli bir il giriniz");
define("DOMAIN_0008", "Lütfen kayıt sahibi için geçerli bir ülke giriniz");
define("DOMAIN_0009", "Lütfen kayıt sahibi için geçerli bir posta kodu giriniz");
define("DOMAIN_0010", "Lütfen kayıt sahibi için geçerli bir telefon giriniz");
define("DOMAIN_0011", "Lütfen kayıt sahibi için geçerli bir faks giriniz");
define("DOMAIN_0012", "Lütfen kayıt sahibi için geçerli bir e-posta giriniz");
define("DOMAIN_0013", "Lütfen geçerli bir yönetici bilgisi giriniz");
define("DOMAIN_0014", "Lütfen kayıt sahibi için geçerli bir kuruluş adı giriniz");
define("DOMAIN_0015", "Lütfen kayıt sahibi için geçerli bir adres 1 giriniz");
define("DOMAIN_0016", "Lütfen kayıt sahibi için geçerli bir adres 2 giriniz");
define("DOMAIN_0017", "Lütfen kayıt sahibi için geçerli bir adres 3 giriniz");
define("DOMAIN_0018", "Lütfen kayıt sahibi için geçerli bir şehir giriniz");
define("DOMAIN_0019", "Lütfen kayıt sahibi için geçerli bir il giriniz");
define("DOMAIN_0020", "Lütfen kayıt sahibi için geçerli bir ülke giriniz");
define("DOMAIN_0021", "Lütfen kayıt sahibi için geçerli bir posta kodu giriniz");
define("DOMAIN_0022", "Lütfen kayıt sahibi için geçerli bir telefon giriniz");
define("DOMAIN_0023", "Lütfen kayıt sahibi için geçerli bir faks giriniz");
define("DOMAIN_0024", "Lütfen kayıt sahibi için geçerli bir e-posta giriniz");
define("DOMAIN_0025", "Lütfen geçerli bir teknik kişi bilgisi giriniz");
define("DOMAIN_0026", "Lütfen teknik kişi için geçerli bir kuruluş adı giriniz");
define("DOMAIN_0027", "Lütfen teknik kişi için geçerli bir adres 1 giriniz");
define("DOMAIN_0028", "Lütfen teknik kişi için geçerli bir adres 2 giriniz");
define("DOMAIN_0029", "Lütfen teknik kişi için geçerli bir adres 3 giriniz");
define("DOMAIN_0030", "Lütfen teknik kişi için geçerli bir şehir giriniz");
define("DOMAIN_0031", "Lütfen teknik kişi için geçerli bir il giriniz");
define("DOMAIN_0032", "Lütfen teknik kişi için geçerli bir ülke giriniz");
define("DOMAIN_0033", "Lütfen teknik kişi için geçerli bir posta kodu giriniz");
define("DOMAIN_0034", "Lütfen teknik kişi için geçerli bir telefon giriniz");
define("DOMAIN_0035", "Lütfen teknik kişi için geçerli bir faks giriniz");
define("DOMAIN_0036", "Lütfen teknik kişi için geçerli bir e-posta giriniz");
define("DOMAIN_0037", "Lütfen geçerli bir faturalandırma kişisi bilgisi giriniz");
define("DOMAIN_0038", "Lütfen faturalandırma için geçerli bir kuruluş adı giriniz");
define("DOMAIN_0039", "Lütfen faturalandırma için geçerli bir adres 1 giriniz");
define("DOMAIN_0040", "Lütfen faturalandırma için geçerli bir adres 2 giriniz");
define("DOMAIN_0041", "Lütfen faturalandırma için geçerli bir adres 3 giriniz");
define("DOMAIN_0042", "Lütfen faturalandırma için geçerli bir şehir giriniz");
define("DOMAIN_0043", "Lütfen faturalandırma için geçerli bir il giriniz");
define("DOMAIN_0044", "Lütfen faturalandırma için geçerli bir ülke giriniz");
define("DOMAIN_0045", "Lütfen faturalandırma için geçerli bir posta kodu giriniz");
define("DOMAIN_0046", "Lütfen faturalandırma için geçerli bir telefon giriniz");
define("DOMAIN_0047", "Lütfen faturalandırma için geçerli bir faks giriniz");
define("DOMAIN_0048", "Lütfen faturalandırma için geçerli bir e-posta giriniz");
define("DOMAIN_0049", "Lütfen geçerli bir kayıt yılı giriniz");
define("DOMAIN_0050", "Lütfen geçerli bir şifre giriniz");
define("DOMAIN_0051", "İki şifre aynı olmalıdır");
define("DOMAIN_0052", "Lütfen geçerli bir dns1 giriniz");
define("DOMAIN_0053", "Lütfen geçerli bir dns2 giriniz");
define("DOMAIN_0054", "İki DNS aynı olamaz");
define("DOMAIN_0055", "Alan adı kaydı için bakiyeniz yetersiz.");
define("DOMAIN_0056", "Sunucuya bağlanılamadı");
define("DOMAIN_0057", "Giriş başarısız");
define("DOMAIN_0058", "İletişim oluşturulamadı");
define("DOMAIN_0059", "Alan adı kaydı başarısız");
define("DOMAIN_0060", "Alan adı şifresi değiştirilemedi");
define("DOMAIN_0061", "Alan adı iletişim bilgisi değiştirilemedi");
define("DOMAIN_0062", "Alan adı iletişim bilgisi başarıyla değiştirildi");
define("DOMAIN_0063", "Alan adı DNS bilgisi değiştirilemedi");
define("DOMAIN_0064", "Alan adı DNS bilgisi başarıyla değiştirildi");
define("DOMAIN_0065", "Lütfen silinecek bir alan adı seçiniz");
define("DOMAIN_0066", "Lütfen yükseltilecek bir alan adı türü seçiniz");
define("DOMAIN_0067", "Bu alan adı türü sistemde zaten mevcut");
define("DOMAIN_0068", "Lütfen geçerli bir alan adı türü giriniz");
define("DOMAIN_0069", "Lütfen geçerli bir alan adı giriniz");
define("DOMAIN_0070", "Girdiğiniz alan adı 63 karakterden uzun olamaz");
define("DOMAIN_0071", "Girdiğiniz alan adı uygun formatta değil");
define("DOMAIN_0072", "Alan adı silme başarısız");
define("DOMAIN_0073", "Alan adı başarıyla silindi");
define("DOMAIN_0074", "Lütfen geçerli bir yıl değeri giriniz");
define("DOMAIN_0075", "Alan adı yenilemek için bakiyeniz yetersiz");
define("DOMAIN_0076", "Lütfen yenilenecek bir alan adı seçiniz");
define("DOMAIN_0077", "Alan adı yenileme başarısız");
define("DOMAIN_0078", "Alan adı başarıyla yenilendi");

define("ALL_0001", "Veri bulma hatası");
define("All_0002", "Ağ hatası");
define("All_0003", "Yapılandırma dosyası hatası");
define("ALL_0004", "Veri güncelleme hatası");
define("ALL_0005", "Veri ekleme hatası");
define("ALL_0006", "Captcha hatası");

define("WHOIS_0001", "Alan adı kayıt için müsaittir.");
define("WHOIS_0002", "Alan adı kayıt için müsaittir (premium)");
define("WHOIS_0003", "Alan adı kayıt için müsait değildir.");
define("WHOIS_0004", "Alan adı kayıt için kontrol edilemedi.");
define("WHOIS_0005", "Alan adı için whois bilgi sorgulaması yapılamadı.");
define("WHOIS_0006", "Yeni sorgu");

define("TEMPLATE_0001", 'Sonucu Kontrol Et');
define("TEMPLATE_0002", 'DNS Yönetimi');
define("TEMPLATE_0003", 'Yeni ad sunucuları ekleyebilir veya mevcut ad sunucularını düzenleyebilirsiniz.');
define("TEMPLATE_0004", 'Alan Adı Listesi');
define("TEMPLATE_0005", 'Alan Adı Yönetim Alanına Hoş Geldiniz! Bu aracı alan adı yönetimini uygulamak için kullanabilirsiniz, alan adı yenileme ve silme, alan adı bilgisi değiştirme ve ad sunucusu değişikliği dahil.');
define("TEMPLATE_0006", 'Alan Adlarınızı Güvence Altına Alın');
define("TEMPLATE_0007", '&nbsp; Alan adı kilitleme, istenmeyen kayıtçı transferlerini ve alan adlarına yönelik DNS değişikliklerini önler.');
define("TEMPLATE_0008", 'Alan Adı Otomatik Yenileme Servisi');
define("TEMPLATE_0009", '&nbsp; Alan Adı Otomatik Yenileme ayarlarını burada değiştirebilirsiniz');
define("TEMPLATE_0010", 'Alan Adı Whois Senkronizasyonu');
define("TEMPLATE_0011", 'Lütfen kullanıcı adını ve alan adını girin');
define("TEMPLATE_0012", 'Alan Adı Whois Senkronizasyonu Sonucu');
define("TEMPLATE_0013", 'E-posta Özelleştirme');
define("TEMPLATE_0014", '&nbsp; Gönderilecek e-postanın ayrıntılarını girin.');
define("TEMPLATE_0015", 'E-posta Bildirim Seçenekleri');
define("TEMPLATE_0016", 'Fonların Yönetimi');
define("TEMPLATE_0017", 'Üye Seviyesini Değiştir');
define("TEMPLATE_0018", 'Fon aktivitesinden sonra üye seviyesini değiştirmek istiyorsanız, bu üye için aşağıdaki panelden yeniden ayarlayın.');
define("TEMPLATE_0019", 'Yönetici Listesi &gt; Yönetici Ekle');
define("TEMPLATE_0020", 'Yönetici Listesi &gt; Yönetici Bilgilerini Düzenle');
define("TEMPLATE_0021", 'Yönetici Listesi');
define("TEMPLATE_0022", "Bu Yöneticiyi silmek istediğinizden emin misiniz?");
define("TEMPLATE_0023", 'Yönetici Listesi &gt; Erişim Ayarları');
define("TEMPLATE_0024", 'Üye Listesi');
define("TEMPLATE_0025", 'Üye Listesi &gt; Üye Bilgilerini Düzenle');
define("TEMPLATE_0026", 'Üye Listesi &gt; Üye bilgilerini göster');
define("TEMPLATE_0027", 'Hesabım');
define("TEMPLATE_0028", 'DNS Düzenle');
define("TEMPLATE_0029", '&nbsp;Alanadı sunucusuna karşılık gelen IP adresini giriniz.');
define("TEMPLATE_0030", 'Ödeme kuruluşu bilgisi');
define("TEMPLATE_0031", '&nbsp;&nbsp; Lütfen ödeme kuruluşu detaylarını güncelleyiniz.');
define("TEMPLATE_0032", 'Alanadı Ayarları');
define("TEMPLATE_0033", 'Alanadı Ayarları &gt; Varsayılan DNS');
define("TEMPLATE_0034", 'Alanadı Ayarları &gt; Alanadı Fiyatlandırması');
define("TEMPLATE_0035", 'Alanadı Türü Ekle');
define("TEMPLATE_0036", 'Lütfen yeni alanadı türü eklemek için SQL sorgularını giriniz. (Örnek sorgular aşağıda gösterilmiştir)');
define("TEMPLATE_0037", 'Alan Adı Yükseltme');
define("TEMPLATE_0038", 'Bu bölüm, yeni alan adlarını alan adı iş kapsamınıza eklemek için kullanılır. Eğer aşağıda ilgilendiğiniz yeni alan adları bulursanız, lütfen bunları seçmekten çekinmeyin.');
define("TEMPLATE_0039", 'Alan Adı Yükseltme Sonucu');
define("TEMPLATE_0040", 'İşlem Geçmişi');
define("TEMPLATE_0041", 'Alan Adı Kaydet');
define("TEMPLATE_0042", "Lütfen doğru kayıt bilgilerini aşağıdaki forma girin.");
define("TEMPLATE_0043", 'Yeni DNS Kaydet');
define("TEMPLATE_0044", '&nbsp;Ad sunucu adını ve IP adresini girin');
define("TEMPLATE_0045", 'Alan Adı DNS Düzenle');
define("TEMPLATE_0046", 'Lütfen geçerli ad sunucusunu aşağıdaki satıra girin.');
define("TEMPLATE_0047", 'Kullanıcı Adı Seç');
define("TEMPLATE_0048", "Lütfen bu alan adını kimin için kaydedecekseniz kullanıcı adını girin.");
define("TEMPLATE_0049", 'Kullanıcı Adı Seç');
define("TEMPLATE_0050", "Lütfen bu alan ad(lar)ını kimin için kaydedecekseniz kullanıcı adını girin.");
define("TEMPLATE_0051", 'Süper Yönetici Alanı &gt; Sistem Ayarı');
define("TEMPLATE_0052", 'Çıkış Yap');
define("TEMPLATE_0053", 'Yardım');
define("TEMPLATE_0054", "Süper Yönetici Alanı");
define("TEMPLATE_0055", 'Yönetici Listesi');
define("TEMPLATE_0056", 'Sistem Ayarı');
define("TEMPLATE_0057", 'E-posta Ayarları');
define("TEMPLATE_0058", 'Geçit Yapılandırma');
define("TEMPLATE_0059", 'Ürün Yönetimi');
define("TEMPLATE_0060", 'Alan Adı Ayarı');
define("TEMPLATE_0061", 'Alan Adı Yükseltme');
define("TEMPLATE_0062", 'Alan Adı Yönetimi');
define("TEMPLATE_0063", 'DNS Yönetimi');
define("TEMPLATE_0064", 'Alan Adı Kaydet');
define("TEMPLATE_0065", 'Alan Adı Senkronizasyonu');
define("TEMPLATE_0066", 'Alan Adı Kilitleme');
define("TEMPLATE_0067", 'Alan Adı Otomatik Yenileme');
define("TEMPLATE_0068", 'Üye Yönetimi');
define("TEMPLATE_0069", 'Üye Listesi');
define("TEMPLATE_0070", 'Hesap Yönetimi');
define("TEMPLATE_0071", 'Fon Yönetimi');
define("TEMPLATE_0072", 'İşlem Sorgulama');
define("TEMPLATE_0073", 'Whois Arama');
define("TEMPLATE_0074", 'Alan Adlarını Kaydet');
define("TEMPLATE_0075", 'Lütfen yıl sayısını seçin');
define("TEMPLATE_0076", 'Alan Adını Kontrol Et');
define("TEMPLATE_0077", 'Lütfen istediğiniz alan adını girin ve kullanılabilirliğini kontrol edin');
define("TEMPLATE_0078", 'Alan Adını Kontrol Et');
define("TEMPLATE_0079", 'Lütfen istediğiniz alan adını girin ve kullanılabilirliğini kontrol edin');
define("TEMPLATE_0080", 'Sonucu Kontrol Et');
define("TEMPLATE_0081", 'Alan Adı Listesi');
define("TEMPLATE_0082", 'Alan Adı Yönetim Alanına Hoş Geldiniz! Bu aracı, alan adı yönetimi uygulamak için kullanabilirsiniz, 
    alan adı yenileme ve silme, alan adı bilgisi değiştirme ve ad sunucusu değişikliği dahil.');
define("TEMPLATE_0083", 'Alan Adı Kaydet');
define("TEMPLATE_0084", 'Lütfen doğru kayıt bilgilerini aşağıdaki forma girin.');
define("TEMPLATE_0085", 'Kayıt Sonucu');
define("TEMPLATE_0086", 'Alan Adını Kontrol Et');
define("TEMPLATE_0087", 'Lütfen istediğiniz alan adını girin ve kullanılabilirliğini kontrol edin.');
define("TEMPLATE_0088", 'Arama Sonucu');
define("TEMPLATE_0089", '&nbsp; Kayıt edilecek alan adlarını seçin.');
define("TEMPLATE_0090", 'Alan Adı İletişim Bilgilerini Düzenle');
define("TEMPLATE_0091", 'Eski bilgilerin yerine geçecek yeni iletişim bilgilerini doğrudan girin.');
define("TEMPLATE_0092", 'Alan Adı DNS Düzenle');
define("TEMPLATE_0093", 'Lütfen geçerli ad sunucusunu aşağıdaki satıra girin.');
define("TEMPLATE_0094", 'Whois');
define("TEMPLATE_0095", 'Lütfen alan adını girin ve whois bilgilerini arayın.');
define("TEMPLATE_0096", 'Whois Sonucu');
define("TEMPLATE_0097", 'Ödeme Onayı');
define("TEMPLATE_0098", '&nbsp;&nbsp; Ödeme yapmaya devam edin.');
define("TEMPLATE_0099", 'Şifreyi Unuttum');
define("TEMPLATE_0100", 'Lütfen doğru kullanıcı adınızı ve E-posta adresinizi girin. Doğru bilgileri girdikten sonra, şifrenizle ilgili bir e-posta otomatik olarak size gönderilecektir.');
define("TEMPLATE_0101", 'Üye Girişi');
define("TEMPLATE_0102", 'Lütfen kullanıcı adınızı ve şifrenizi girin.');
define("TEMPLATE_0103", 'Hesabım');
define("TEMPLATE_0104", 'Sipariş Geçmişi');
define("TEMPLATE_0105", 'Fatura Bilgileri');
define("TEMPLATE_0106", '&nbsp;&nbsp; Lütfen ödeme yöntemini ve detaylarını güncelleyin.');
define("TEMPLATE_0107", 'Ödeme Sonucu');
define("TEMPLATE_0108", '&nbsp;&nbsp; Yapılan ödemenin sonuçları.');
define("TEMPLATE_0109", 'Fonları Yönet');
define("TEMPLATE_0110", '&nbsp;&nbsp; Hesabınıza fon ekleyin.');
define("TEMPLATE_0111", 'Üye Girişi');
define("TEMPLATE_0112", 'Lütfen kullanıcı adınızı ve şifrenizi girin.');
define("TEMPLATE_0113", 'Kayıt Ol');
define("TEMPLATE_0114", 'Üyemiz olma yolunda hoş geldiniz! Yıldız (*) ile işaretlenmiş alanların tamamını doldurmalısınız.');
define("TEMPLATE_0115", 'Kayıt Olma Sonucu');
define("TEMPLATE_0116", 'Hesap Bilgilerini Güncelle');
define("TEMPLATE_0117", 'Lütfen yeni hesap bilgilerinizi doğrudan girin. Şifreyi değiştirmek istiyorsanız, önce eski şifrenizi sonra yeni şifrenizi girin. Şifreyi değiştirmek istemiyorsanız, şifre satırlarını boş bırakın.');
define("TEMPLATE_0118", "Sistem Hatası");
define("TEMPLATE_0119", 'Sistem anasayfası');
define("TEMPLATE_0120", "Hoşgeldiniz");
define("TEMPLATE_0121", '<p>- ÜCRETSİZ ÜYELİK</p>'
.'<p>- PAYPAL veya KREDİ KARTIYLA ÖDEME YAPABİLİRSİNİZ</p>'
.'<p>- HESAP BAKİYENİZİN SON KULLANMA TARİHİ YOKTUR</p>'
.'<p>- İHTİYACINIZ OLAN KADAR BAKİYE YÜKLEYEBİLİRSİNİZ</p>'
.'<p>- KOLAY ve SADE YÖNETİM TASARIMI</p>');
define("TEMPLATE_0122", 'Sistem Durumu');
define("TEMPLATE_0123", "Üzgünüz, sistem bakımda.");
define("TEMPLATE_0124", 'Anasayfa');
define("TEMPLATE_0125", 'Hesabım');
define("TEMPLATE_0126", 'Çıkış Yap');
define("TEMPLATE_0127", "İş Araçları");
define("TEMPLATE_0128", 'Whois Arama');
define("TEMPLATE_0129", 'Alan Adı Kaydet');
define("TEMPLATE_0130", 'Alan Adı Yönetimi');
define("TEMPLATE_0131", 'Üye Araçları');
define("TEMPLATE_0132", 'Hesap Bilgilerini Düzenle');
define("TEMPLATE_0133", 'Şifremi Unuttum');
define("TEMPLATE_0134", 'İşlem Geçmişi');
define("TEMPLATE_0135", 'Ürün Yönetimi');
define("TEMPLATE_0136", 'DNS Yönetimi');
define("TEMPLATE_0137", 'Alan Adı Otomatik Yenileme');
define("TEMPLATE_0138", 'Alan Adı Kilitleme');
define("TEMPLATE_0139", 'Fon Yönetimi');
define("TEMPLATE_0140", 'Fonları Yönet');
define("TEMPLATE_0141", 'Üye Girişi');
define("TEMPLATE_0142", 'Whois Arama');
define("TEMPLATE_0143", 'Kayıt Ol');
define("TEMPLATE_0144", 'Alan Adı Kaydet');
define("TEMPLATE_0145", 'Şifremi Unuttum');
define("TEMPLATE_0146", 'Giriş Yap');
define("TEMPLATE_0147", 'Diğer operasyonlar');

// gelecek ihtiyaçlar için rezerve edildi.
define("TEMPLATE_0148", '');
define("TEMPLATE_0149", '');
define("TEMPLATE_0150", '');
define("TEMPLATE_0151", '');
define("TEMPLATE_0152", '');
define("TEMPLATE_0153", '');
define("TEMPLATE_0154", '');
define("TEMPLATE_0155", '');
define("TEMPLATE_0156", '');
define("TEMPLATE_0157", '');
define("TEMPLATE_0158", '');
define("TEMPLATE_0159", '');
?>
