<?php
define("MEMBER_0001", "Proporcione un valor válido para su nombre de usuario");
define("MEMBER_0002", "Proporcione un valor válido para su contraseña");
define("MEMBER_0003", "Proporcione un valor válido para su registrante");
define("MEMBER_0004", "Proporcione un valor válido para su organización");
define("MEMBER_0005", "Proporcione un valor válido para su calle 1");
define("MEMBER_0006", "Proporcione un valor válido para su calle 2");
define("MEMBER_0007", "Proporcione un valor válido para su calle 3");
define("MEMBER_0008", "Proporcione un valor válido para su ciudad");
define("MEMBER_0009", "Proporcione un valor válido para su provincia");
define("MEMBER_0010", "Proporcione un valor válido para su país");
define("MEMBER_0011", "Proporcione un valor válido para su código postal");
define("MEMBER_0012", "Proporcione un valor válido para su teléfono");
define("MEMBER_0013", "Proporcione un valor válido para su fax");
define("MEMBER_0014", "Proporcione un valor válido para su correo electrónico");
define("MEMBER_0015", "Proporcione un valor válido para su mensaje");
define("MEMBER_0016", "El miembro ya existe. Seleccione otro nombre de usuario para registrarse");
define("MEMBER_0017", "Proporcione un valor válido para su nueva contraseña");
define("MEMBER_0018", "Las dos contraseñas deben ser iguales");
define("MEMBER_0019", "Proporcione un valor válido para su contraseña anterior");
define("MEMBER_0020", "La información del miembro se ha actualizado correctamente");
define("MEMBER_0021", "Proporcione un valor válido para su nombre de usuario");
define("MEMBER_0022", "Proporcione un valor válido para su contraseña");
define("MEMBER_0023", "Error de inicio de sesión, introduzca el nombre de usuario y la contraseña correctos");
define("MEMBER_0024", "Error de inicio de sesión, la cuenta ha sido bloqueada");
define("MEMBER_0025", "Se ha enviado un correo electrónico con la contraseña a su correo electrónico");
define("MEMBER_0026", "No se ha encontrado información del miembro; proporcione información válida");
define("MEMBER_0027", "Proporcione nuevamente un valor válido para su contraseña");
define("MEMBER_0028", "Su contraseña");
define("MEMBER_0029", "Proporcione un valor válido para el número de identificación de la tarjeta de crédito");
define("MEMBER_0030", "Proporcione un valor válido para la dirección");
define("MEMBER_0031", "Proporcione un valor válido para el nombre de la tarjeta de crédito");
define("MEMBER_0032", "Proporcione un valor válido para el número de la tarjeta de crédito");
define("MEMBER_0033", "Proporcione un valor válido para la fecha");
define("MEMBER_0034", "Proporcione un valor válido para el año");
define("MEMBER_0035", "Proporcione un valor válido para el nombre");
define("MEMBER_0036", "Los dominios .us deben registrarse por al menos 2 años");
define("MEMBER_0037", "La cuenta no tiene saldo suficiente.");
define("MEMBER_0038", "Ya existe otra cuenta con esa dirección de correo electrónico.");


define("ADMIN_0001", "Proporcione un nombre de usuario válido");
define("ADMIN_0002", "Proporcione un tipo válido");
define("ADMIN_0003", "Proporcione un importe válido");
define("ADMIN_0004", "Proporcione una nota válida");
define("ADMIN_0005", "El miembro no existe");
define("ADMIN_0006", "La actualización de la cuenta falló");
define("ADMIN_0007", "Cuenta actualizada correctamente");
define("ADMIN_0008", "Proporcione un valor válido para el nombre del administrador");
define("ADMIN_0009", "Proporcione un valor válido para el departamento del administrador");
define("ADMIN_0010", "Proporcione un valor válido para la contraseña del administrador");
define("ADMIN_0011", "Las dos contraseñas deben ser iguales");
define("ADMIN_0012", "Administrador añadido correctamente");
define("ADMIN_0013", "No se pudo encontrar el administrador");
define("ADMIN_0014", "No puede modificar la cuenta de superadministrador");
define("ADMIN_0015", "Información del administrador modificada correctamente");
define("ADMIN_0016", "Administrador eliminado correctamente");
define("ADMIN_0017", "Tareas del administrador configuradas correctamente");
define("ADMIN_0018", "No se pudo encontrar el miembro");
define("ADMIN_0019", "Iniciar");
define("ADMIN_0020", "Detener");
define("ADMIN_0021", "Miembro eliminado correctamente");
define("ADMIN_0022", "No se pudo encontrar el producto");
define("ADMIN_0023", "Dominio iniciado correctamente");
define("ADMIN_0024", "Dominio detenido correctamente");
define("ADMIN_0025", "Proporcione un DNS primario válido");
define("ADMIN_0026", "Proporcione un DNS secundario válido");
define("ADMIN_0027", "DNS predeterminado modificado correctamente");
define("ADMIN_0028", "Precios modificados correctamente");
define("ADMIN_0029", "Proporcione un diseño de sitio web válido");
define("ADMIN_0030", "Proporcione un título válido");
define("ADMIN_0031", "Proporcione un copyright válido");
define("ADMIN_0032", "Proporcione un tamaño de página válido; el valor debe estar entre 1 y 50");
define("ADMIN_0033", "Proporcione un estado del sistema válido");
define("ADMIN_0034", "Sistema actualizado correctamente");
define("ADMIN_0035", "Lo sentimos, no tiene acceso para realizar este proceso");
define("ADMIN_0036", "Proporcione un ID de revendedor válido");
define("ADMIN_0037", "Proporcione una contraseña de revendedor válida");
define("ADMIN_0038", "Proporcione un host de servidor válido");
define("ADMIN_0039", "Proporcione un puerto de servidor válido");
define("ADMIN_0040", "La actualización del producto falló");
define("ADMIN_0041", "Los campos no pueden estar vacíos");
define("ADMIN_0042", "¡Configuración actualizada correctamente!");
define("ADMIN_0043", "Correo electrónico de prueba enviado correctamente.");
define("ADMIN_0044", "¡La prueba de configuración de correo electrónico falló!");

define("DOMAIN_0001", "Proporcione un valor válido para su registrante");
define("DOMAIN_0002", "Proporcione un valor válido para la organización del registrante");
define("DOMAIN_0003", "Proporcione un valor válido para la dirección 1 del registrante");
define("DOMAIN_0004", "Proporcione un valor válido para la dirección 2 del registrante");
define("DOMAIN_0005", "Proporcione un valor válido para la dirección 3 del registrante");
define("DOMAIN_0006", "Proporcione un valor válido para la ciudad del registrante");
define("DOMAIN_0007", "Proporcione un valor válido para la provincia del registrante");
define("DOMAIN_0008", "Proporcione un valor válido para el país del registrante");
define("DOMAIN_0009", "Proporcione un valor válido para el código postal del registrante");
define("DOMAIN_0010", "Proporcione un valor válido para el teléfono del registrante");
define("DOMAIN_0011", "Proporcione un valor válido para el fax del registrante");
define("DOMAIN_0012", "Proporcione un valor válido para el correo electrónico del registrante");
define("DOMAIN_0013", "Proporcione un valor válido para su administrador");
define("DOMAIN_0014", "Proporcione un valor válido para la organización del registrante");
define("DOMAIN_0015", "Proporcione un valor válido para la dirección 1 del registrante");
define("DOMAIN_0016", "Proporcione un valor válido para la dirección 2 del registrante");
define("DOMAIN_0017", "Proporcione un valor válido para la dirección 3 del registrante");
define("DOMAIN_0018", "Proporcione un valor válido para la ciudad del registrante");
define("DOMAIN_0019", "Proporcione un valor válido para la provincia del registrante");
define("DOMAIN_0020", "Proporcione un valor válido para el país del registrante");
define("DOMAIN_0021", "Proporcione un valor válido para el código postal del registrante");
define("DOMAIN_0022", "Proporcione un valor válido para el teléfono del registrante");
define("DOMAIN_0023", "Proporcione un valor válido para el fax del registrante");
define("DOMAIN_0024", "Proporcione un valor válido para el correo electrónico del registrante");
define("DOMAIN_0025", "Proporcione un valor válido para su contacto técnico");
define("DOMAIN_0026", "Proporcione un valor válido para la organización del contacto técnico");
define("DOMAIN_0027", "Proporcione un valor válido para la dirección 1 del contacto técnico");
define("DOMAIN_0028", "Proporcione un valor válido para la dirección 2 del contacto técnico");
define("DOMAIN_0029", "Proporcione un valor válido para la dirección 3 del contacto técnico");
define("DOMAIN_0030", "Proporcione un valor válido para la ciudad del contacto técnico");
define("DOMAIN_0031", "Proporcione un valor válido para la provincia del contacto técnico");
define("DOMAIN_0032", "Proporcione un valor válido para el país del contacto técnico");
define("DOMAIN_0033", "Proporcione un valor válido para el código postal del contacto técnico");
define("DOMAIN_0034", "Proporcione un valor válido para el teléfono del contacto técnico");
define("DOMAIN_0035", "Proporcione un valor válido para el fax del contacto técnico");
define("DOMAIN_0036", "Proporcione un valor válido para el correo electrónico del contacto técnico");
define("DOMAIN_0037", "Proporcione un valor válido para su contacto de facturación");
define("DOMAIN_0038", "Proporcione un valor válido para la organización del contacto de facturación");
define("DOMAIN_0039", "Proporcione un valor válido para la dirección 1 del contacto de facturación");
define("DOMAIN_0040", "Proporcione un valor válido para la dirección 2 del contacto de facturación");
define("DOMAIN_0041", "Proporcione un valor válido para la dirección 3 del contacto de facturación");
define("DOMAIN_0042", "Proporcione un valor válido para la ciudad del contacto de facturación");
define("DOMAIN_0043", "Proporcione un valor válido para la provincia del contacto de facturación");
define("DOMAIN_0044", "Proporcione un valor válido para el país del contacto de facturación");
define("DOMAIN_0045", "Proporcione un valor válido para el código postal del contacto de facturación");
define("DOMAIN_0046", "Proporcione un valor válido para el teléfono del contacto de facturación");
define("DOMAIN_0047", "Proporcione un valor válido para el fax del contacto de facturación");
define("DOMAIN_0048", "Proporcione un valor válido para el correo electrónico del contacto de facturación");
define("DOMAIN_0049", "Proporcione un valor válido para el año de registro");
define("DOMAIN_0050", "Proporcione un valor válido para la contraseña");
define("DOMAIN_0051", "Las dos contraseñas deben ser iguales");
define("DOMAIN_0052", "Proporcione un valor válido para DNS1");
define("DOMAIN_0053", "Proporcione un valor válido para DNS2");
define("DOMAIN_0054", "Los dos DNS no pueden ser iguales");
define("DOMAIN_0055", "Su saldo no es suficiente para registrar el dominio.");
define("DOMAIN_0056", "Error al conectar con el servidor");
define("DOMAIN_0057", "Error de inicio de sesión");
define("DOMAIN_0058", "Error al crear el contacto");
define("DOMAIN_0059", "Error al registrar el dominio");
define("DOMAIN_0060", "Error al modificar la contraseña del dominio");
define("DOMAIN_0061", "Error al modificar el contacto del dominio");
define("DOMAIN_0062", "Contacto del dominio modificado correctamente");
define("DOMAIN_0063", "Error al modificar el DNS del dominio");
define("DOMAIN_0064", "DNS del dominio modificado correctamente");
define("DOMAIN_0065", "Seleccione un dominio para eliminar");
define("DOMAIN_0066", "Seleccione un tipo de dominio para actualizar");
define("DOMAIN_0067", "El tipo de dominio ya existe en el sistema");
define("DOMAIN_0068", "Proporcione un valor válido para su tipo de dominio");
define("DOMAIN_0069", "Proporcione un valor válido para su dominio");
define("DOMAIN_0070", "El dominio proporcionado no puede tener más de 63 caracteres");
define("DOMAIN_0071", "El dominio proporcionado no tiene el formato adecuado");
define("DOMAIN_0072", "Error al eliminar el dominio");
define("DOMAIN_0073", "Dominio eliminado correctamente");
define("DOMAIN_0074", "Proporcione un valor válido para el año");
define("DOMAIN_0075", "Su saldo no es suficiente para renovar el dominio");
define("DOMAIN_0076", "Seleccione un dominio para renovar");
define("DOMAIN_0077", "Error al renovar el dominio");
define("DOMAIN_0078", "Dominio renovado correctamente");

define("ALL_0001", "Error al buscar datos");
define("All_0002", "Error de red");
define("All_0003", "Error del archivo de configuración");
define("ALL_0004", "Error al actualizar datos");
define("ALL_0005", "Error al insertar datos");
define("ALL_0006", "Error de captcha");

define("WHOIS_0001", "El dominio está disponible para registro.");
define("WHOIS_0002", "El dominio está disponible para registro (premium).");
define("WHOIS_0003", "El dominio no está disponible para registro.");
define("WHOIS_0004", "No se pudo comprobar la disponibilidad del dominio para registro.");
define("WHOIS_0005", "No se pudo consultar la información Whois del dominio.");
define("WHOIS_0006", "Nueva consulta");

define("TEMPLATE_0001", 'Resultado de comprobación');
define("TEMPLATE_0002", 'Gestionar DNS');
define("TEMPLATE_0003", 'Puede añadir nuevos servidores de nombres o editar los servidores de nombres existentes.');
define("TEMPLATE_0004", 'Lista de dominios');
define("TEMPLATE_0005", '¡Bienvenido al área de gestión de dominios!	Puede usar esta herramienta para implementar la gestión de dominios, incluida la renovación y eliminación de dominios, la modificación de información del dominio y el cambio de servidores de nombres.');
define("TEMPLATE_0006", 'Proteja sus dominios');
define("TEMPLATE_0007", '&nbsp; El bloqueo de dominio evita transferencias de registrador no deseadas y cambios de DNS en los nombres de dominio');
define("TEMPLATE_0008", 'Servicio de renovación automática de dominios');
define("TEMPLATE_0009", '&nbsp; Cambie aquí la configuración de renovación automática del dominio');
define("TEMPLATE_0010", 'Sincronización Whois del dominio');
define("TEMPLATE_0011", 'Introduzca el nombre de usuario y el nombre de dominio');
define("TEMPLATE_0012", 'Resultado de sincronización Whois del dominio');
define("TEMPLATE_0013", 'Personalización de correo electrónico');
define("TEMPLATE_0014", '&nbsp; Introduzca los detalles del correo electrónico que se enviará.');
define("TEMPLATE_0015", 'Opciones de notificación por correo electrónico');
define("TEMPLATE_0016", 'Gestión de fondos');
define("TEMPLATE_0017", 'Modificar nivel de miembro');
define("TEMPLATE_0018", 'Si desea modificar el nivel del miembro después de la actividad de fondos, restablézcalo para este miembro en el siguiente panel. ');
define("TEMPLATE_0019", 'Lista de administradores &gt; Añadir administrador');
define("TEMPLATE_0020", 'Lista de administradores &gt; Modificar información del administrador');
define("TEMPLATE_0021", 'Lista de administradores');
define("TEMPLATE_0022", "¿Está seguro de que desea eliminar este administrador?");
define("TEMPLATE_0023", 'Lista de administradores &gt; Configuración de acceso');
define("TEMPLATE_0024", 'Lista de miembros');
define("TEMPLATE_0025", 'Lista de miembros &gt; Modificar información del miembro');
define("TEMPLATE_0026", 'Lista de miembros &gt; Ver información del miembro');
define("TEMPLATE_0027", 'Mi cuenta');
define("TEMPLATE_0028", 'Editar DNS');
define("TEMPLATE_0029", '&nbsp;Introduzca la IP correspondiente al servidor de nombres.');
define("TEMPLATE_0030", 'Información de la pasarela de pago');
define("TEMPLATE_0031", '&nbsp;&nbsp; Actualice los detalles de la pasarela de pago.');
define("TEMPLATE_0032", 'Configuración de dominio');
define("TEMPLATE_0033", 'Configuración de dominio &gt; DNS predeterminado');
define("TEMPLATE_0034", 'Configuración de dominio &gt; Precios de dominios');
define("TEMPLATE_0035", 'Añadir tipo de dominio');
define("TEMPLATE_0036", 'Introduzca las consultas para añadir el nuevo tipo de dominio (las consultas de ejemplo se muestran a continuación)');
define("TEMPLATE_0037", 'Actualización de dominio');
define("TEMPLATE_0038", 'Esta sección se utiliza para añadir nuevos dominios al alcance de su negocio de dominios. Si encuentra abajo nuevos dominios que le interesen, no dude en seleccionarlos.');
define("TEMPLATE_0039", 'Resultado de actualización de dominio');
define("TEMPLATE_0040", 'Historial de transacciones');
define("TEMPLATE_0041", 'Registrar dominio');
define("TEMPLATE_0042", "Introduzca la información de registro correcta en el siguiente formulario.");
define("TEMPLATE_0043", 'Registrar nuevo DNS');
define("TEMPLATE_0044", '&nbsp;Introduzca el nombre del servidor de nombres y la IP');
define("TEMPLATE_0045", 'Modificar DNS del dominio');
define("TEMPLATE_0046", 'Introduzca el servidor de nombres válido en la siguiente línea.');
define("TEMPLATE_0047", 'Seleccionar nombre de usuario');
define("TEMPLATE_0048", "Introduzca el nombre de usuario para el que registrará este dominio.");
define("TEMPLATE_0049", 'Seleccionar nombre de usuario');
define("TEMPLATE_0050", "Introduzca el nombre de usuario para el que registrará este/estos dominio(s).");
define("TEMPLATE_0051", 'Área de superadministrador &gt; Configuración del sistema');
define("TEMPLATE_0052", 'Cerrar sesión');
define("TEMPLATE_0053", 'Ayuda');
define("TEMPLATE_0054", "Área de superadministrador");
define("TEMPLATE_0055", 'Lista de administradores');
define("TEMPLATE_0056", 'Configuración del sistema');
define("TEMPLATE_0057", 'Configuración de correo electrónico');
define("TEMPLATE_0058", 'Configurar pasarela');
define("TEMPLATE_0059", 'Gestión de productos');
define("TEMPLATE_0060", 'Configuración de dominio');
define("TEMPLATE_0061", 'Actualización de dominio');
define("TEMPLATE_0062", 'Gestionar dominio');
define("TEMPLATE_0063", 'Gestionar DNS');
define("TEMPLATE_0064", 'Registrar dominio');
define("TEMPLATE_0065", 'Sincronización de dominio');
define("TEMPLATE_0066", 'Bloqueo de dominio');
define("TEMPLATE_0067", 'Renovación automática de dominio');
define("TEMPLATE_0068", 'Gestión de miembros');
define("TEMPLATE_0069", 'Lista de miembros');
define("TEMPLATE_0070", 'Gestión de cuentas');
define("TEMPLATE_0071", 'Gestión de fondos');
define("TEMPLATE_0072", 'Consultar transacción');
define("TEMPLATE_0073", 'Búsqueda Whois');
define("TEMPLATE_0074", 'Registrar dominios');
define("TEMPLATE_0075", 'Seleccione el número de años');
define("TEMPLATE_0076", 'Comprobar dominio');
define("TEMPLATE_0077", 'Introduzca el nombre de dominio deseado para comprobar su disponibilidad');
define("TEMPLATE_0078", 'Comprobar dominio');
define("TEMPLATE_0079", 'Introduzca el nombre de dominio deseado para comprobar su disponibilidad');
define("TEMPLATE_0080", 'Resultado de comprobación');
define("TEMPLATE_0081", 'Lista de dominios');
define("TEMPLATE_0082", '¡Bienvenido al área de gestión de dominios! Puede usar esta herramienta para implementar la gestión de dominios, incluida la renovación y eliminación de dominios, la modificación de información del dominio y el cambio de servidores de nombres.');
define("TEMPLATE_0083", 'Registrar dominio');
define("TEMPLATE_0084", 'Introduzca la información de registro correcta en el siguiente formulario.');
define("TEMPLATE_0085", 'Resultado de registro');
define("TEMPLATE_0086", 'Comprobar dominio');
define("TEMPLATE_0087", 'Introduzca el nombre de dominio deseado para comprobar su disponibilidad');
define("TEMPLATE_0088", 'Resultado de búsqueda');
define("TEMPLATE_0089", '&nbsp; Seleccione los dominios que se registrarán ');
define("TEMPLATE_0090", 'Modificar contacto del dominio');
define("TEMPLATE_0091", 'Introduzca directamente la nueva información de contacto para reemplazar la anterior.');
define("TEMPLATE_0092", 'Modificar DNS del dominio');
define("TEMPLATE_0093", 'Introduzca el servidor de nombres válido en la siguiente línea.');
define("TEMPLATE_0094", 'Whois');
define("TEMPLATE_0095", 'Introduzca el nombre de dominio para buscar su información Whois');
define("TEMPLATE_0096", 'Resultado Whois');
define("TEMPLATE_0097", 'Confirmar pago');
define("TEMPLATE_0098", '&nbsp;&nbsp; Continúe para realizar el pago.');
define("TEMPLATE_0099", 'Olvidé mi contraseña');
define("TEMPLATE_0100", 'Introduzca su nombre de usuario y dirección de correo electrónico correctos para recuperar la contraseña. Una vez que complete la información correcta, se le enviará automáticamente un correo electrónico con su nueva contraseña.');
define("TEMPLATE_0101", 'Inicio de sesión de miembro');
define("TEMPLATE_0102", 'Introduzca su nombre de usuario y contraseña para iniciar sesión.');
define("TEMPLATE_0103", 'Mi cuenta');
define("TEMPLATE_0104", 'Historial de pedidos');
define("TEMPLATE_0105", 'Información de facturación');
define("TEMPLATE_0106", '&nbsp;&nbsp; Actualice el método de pago y los detalles.');
define("TEMPLATE_0107", 'Resultado de pago');
define("TEMPLATE_0108", '&nbsp;&nbsp; Resultados del pago realizado.');
define("TEMPLATE_0109", 'Gestionar fondos');
define("TEMPLATE_0110", '&nbsp;&nbsp; Añada fondos a su cuenta.');
define("TEMPLATE_0111", 'Inicio de sesión de miembro');
define("TEMPLATE_0112", 'Introduzca su nombre de usuario y contraseña para iniciar sesión.');
define("TEMPLATE_0113", 'Registrarse');
define("TEMPLATE_0114", '¡Bienvenido a ser nuestro miembro! La línea con asterisco (*) debe completarse por completo.');
define("TEMPLATE_0115", 'Resultado de registro');
define("TEMPLATE_0116", 'Actualizar información de la cuenta');
define("TEMPLATE_0117", 'Introduzca directamente la nueva información de su cuenta. Si desea cambiar la contraseña de la cuenta, introduzca primero la anterior y luego la nueva. Si no desea cambiarla, deje las líneas de contraseña en blanco.');
define("TEMPLATE_0118", "Error del sistema");
define("TEMPLATE_0119", 'Página principal del sistema');
define("TEMPLATE_0120", "Bienvenido");
define("TEMPLATE_0121", '<p>- MEMBRESÍA GRATUITA</p><p>- PAGUE CON PAYPAL O TARJETA DE CRÉDITO</p><p>- LOS FONDOS NO CADUCAN</p><p>- AÑADA TANTOS FONDOS COMO NECESITE</p><p>- GESTIÓN FÁCIL Y SENCILLA</p>');
define("TEMPLATE_0122", 'Estado del sistema');
define("TEMPLATE_0123", "Lo sentimos, el sistema está en mantenimiento");
define("TEMPLATE_0124", 'Inicio');
define("TEMPLATE_0125", 'Mi cuenta');
define("TEMPLATE_0126", 'Cerrar sesión');
define("TEMPLATE_0127", "Herramientas de negocio");
define("TEMPLATE_0128", 'Búsqueda Whois');
define("TEMPLATE_0129", 'Registrar dominio');
define("TEMPLATE_0130", 'Gestionar dominio');
define("TEMPLATE_0131", 'Herramientas de miembros');
define("TEMPLATE_0132", 'Modificar información de la cuenta');
define("TEMPLATE_0133", 'Olvidé mi contraseña');
define("TEMPLATE_0134", 'Historial de transacciones');
define("TEMPLATE_0135", 'Gestión de productos');
define("TEMPLATE_0136", 'Gestionar DNS');
define("TEMPLATE_0137", 'Renovación automática de dominio');
define("TEMPLATE_0138", 'Bloqueo de dominio');
define("TEMPLATE_0139", 'Gestión de fondos');
define("TEMPLATE_0140", 'Gestionar fondos');
define("TEMPLATE_0141", 'Inicio de sesión de miembro');
define("TEMPLATE_0142", 'Búsqueda Whois');
define("TEMPLATE_0143", 'Registrarse');
define("TEMPLATE_0144", 'Registrar dominio');
define("TEMPLATE_0145", 'Olvidé mi contraseña');
define("TEMPLATE_0146", 'Iniciar sesión');
define("TEMPLATE_0147", 'Otra operación');

define("TEMPLATE_LANG", 'Español');
define("TEMPLATE_LANG_JS", "Por favor, guarde primero cualquier trabajo u operación que no haya guardado.\n\n¿Desea recargar la página ahora?\n\nSí = No tengo nada sin guardar, ¡recargar!\nNo = Guardaré primero y recargaré más tarde.");

// reserved for future use.
define("TEMPLATE_0148", '');
define("TEMPLATE_0149", '');
define("TEMPLATE_0150", '');
define("TEMPLATE_0151", '');
define("TEMPLATE_0152", '');
define("TEMPLATE_0153", '');
define("TEMPLATE_0154", '');
define("TEMPLATE_0155", '');
define("TEMPLATE_0156", '');
define("TEMPLATE_0157", '');
define("TEMPLATE_0158", '');
define("TEMPLATE_0159", '');
?>
