insert into country(country_name, country_code) values ("AFGHANISTAN", "AF");
insert into country(country_name, country_code) values ("ALBANIA", "AL");
insert into country(country_name, country_code) values ("BOTSWANA", "BW");
insert into country(country_name, country_code) values ("ALGERIA", "DZ");
insert into country(country_name, country_code) values ("AMERICAN SAMOA", "AS");
insert into country(country_name, country_code) values ("ANDORRA", "AD");
insert into country(country_name, country_code) values ("ANGOLA", "AO");
insert into country(country_name, country_code) values ("ANGUILLA", "AI");
insert into country(country_name, country_code) values ("ANTARCTICA", "AQ");
insert into country(country_name, country_code) values ("ANTIGUA AND BARBUDA", "AG");
insert into country(country_name, country_code) values ("ARGENTINA", "AR");
insert into country(country_name, country_code) values ("ARMENIA", "AM");
insert into country(country_name, country_code) values ("ARUBA", "AW");
insert into country(country_name, country_code) values ("AUSTRALIA", "AU");
insert into country(country_name, country_code) values ("AUSTRI", "AT");
insert into country(country_name, country_code) values ("AZERBAIJAN", "AZ");
insert into country(country_name, country_code) values ("BAHAMAS", "BS");
insert into country(country_name, country_code) values ("BAHRAIN", "BH");
insert into country(country_name, country_code) values ("BANGLADESH", "BD");
insert into country(country_name, country_code) values ("BARBADOS", "BB");
insert into country(country_name, country_code) values ("BELARUS", "BY");
insert into country(country_name, country_code) values ("BELGIUM", "BE");
insert into country(country_name, country_code) values ("BELIZE", "BZ");
insert into country(country_name, country_code) values ("BENIN", "BJ");
insert into country(country_name, country_code) values ("BERMUDA", "BM");
insert into country(country_name, country_code) values ("BHUTAN", "BT");
insert into country(country_name, country_code) values ("BOLIVIA", "BO");
insert into country(country_name, country_code) values ("BOSNIA AND HERZEGOVINA", "BA");
insert into country(country_name, country_code) values ("BOUVET ISLAND", "BV");
insert into country(country_name, country_code) values ("BRAZIL", "BR");
insert into country(country_name, country_code) values ("BRITISH INDIAN OCEAN TERRITORY", "IO");
insert into country(country_name, country_code) values ("BRUNEI DARUSSALAM", "BN");
insert into country(country_name, country_code) values ("BULGARIA", "BG");
insert into country(country_name, country_code) values ("BURKINA FASO", "BF");
insert into country(country_name, country_code) values ("BURUNDI", "BI");
insert into country(country_name, country_code) values ("CAMBODIA", "KH");
insert into country(country_name, country_code) values ("CAMEROON", "CM");
insert into country(country_name, country_code) values ("CANADA", "CA");
insert into country(country_name, country_code) values ("CAPE VERDE", "CV");
insert into country(country_name, country_code) values ("CAYMAN ISLANDS", "KY");
insert into country(country_name, country_code) values ("CENTRAL AFRICAN REPUBLIC", "CF");
insert into country(country_name, country_code) values ("CHAD", "TD");
insert into country(country_name, country_code) values ("CHILE", "CL");
insert into country(country_name, country_code) values ("CHINA", "CN");
insert into country(country_name, country_code) values ("CHRISTMAS ISLAND", "CX");
insert into country(country_name, country_code) values ("COCOS (KEELING) ISLANDS", "CC");
insert into country(country_name, country_code) values ("COLOMBIA", "CO");
insert into country(country_name, country_code) values ("COMOROS", "KM");
insert into country(country_name, country_code) values ("CONGO", "CG");
insert into country(country_name, country_code) values ("CONGO, THE DEMOCRATIC REPUBLIC OF THE", "CD");
insert into country(country_name, country_code) values ("COOK ISLANDS", "CK");
insert into country(country_name, country_code) values ("COSTA RICA", "CR");
insert into country(country_name, country_code) values ("C?TE D' IVOIRE", "CI");
insert into country(country_name, country_code) values ("CROATIA", "HR");
insert into country(country_name, country_code) values ("CUBA", "CU");
insert into country(country_name, country_code) values ("CYPRUS", "CY");
insert into country(country_name, country_code) values ("CZECH REPUBLIC", "CZ");
insert into country(country_name, country_code) values ("DENMARK", "DK");
insert into country(country_name, country_code) values ("DJIBOUTI", "DJ");
insert into country(country_name, country_code) values ("DOMINICA", "DM");
insert into country(country_name, country_code) values ("DOMINICAN REPUBLIC", "DO");
insert into country(country_name, country_code) values ("EAST TIMOR", "TP");
insert into country(country_name, country_code) values ("ECUADOR", "EC");
insert into country(country_name, country_code) values ("EGYPT", "EG");
insert into country(country_name, country_code) values ("EL SALVADOR", "SV");
insert into country(country_name, country_code) values ("EQUATORIAL GUINEA", "GQ");
insert into country(country_name, country_code) values ("ERITREA", "ER");
insert into country(country_name, country_code) values ("ESTONIA", "EE");
insert into country(country_name, country_code) values ("ETHIOPIA", "ET");
insert into country(country_name, country_code) values ("FALKLAND ISLANDS (MALVINAS)", "FK");
insert into country(country_name, country_code) values ("FAROE ISLANDS", "FO");
insert into country(country_name, country_code) values ("FIJI", "FJ");
insert into country(country_name, country_code) values ("FINLAND", "FI");
insert into country(country_name, country_code) values ("FRANCE", "FR");
insert into country(country_name, country_code) values ("FRENCH GUIANA", "GF");
insert into country(country_name, country_code) values ("FRENCH POLYNESIA", "PF");
insert into country(country_name, country_code) values ("FRENCH SOUTHERN TERRITORIES", "TF");
insert into country(country_name, country_code) values ("GABON", "GA");
insert into country(country_name, country_code) values ("GAMBIA", "GM");
insert into country(country_name, country_code) values ("GEORGIA", "GE");
insert into country(country_name, country_code) values ("GERMANY", "DE");
insert into country(country_name, country_code) values ("GHANA", "GH");
insert into country(country_name, country_code) values ("GIBRALTAR", "GI");
insert into country(country_name, country_code) values ("GREECE", "GR");
insert into country(country_name, country_code) values ("GREENLAND", "GL");
insert into country(country_name, country_code) values ("GRENADA", "GD");
insert into country(country_name, country_code) values ("GUADELOUPE", "GP");
insert into country(country_name, country_code) values ("GUAM", "GU");
insert into country(country_name, country_code) values ("GUATEMALA", "GT");
insert into country(country_name, country_code) values ("GUINEA", "GN");
insert into country(country_name, country_code) values ("GUINEA-BISSAU", "GW");
insert into country(country_name, country_code) values ("GUYANA", "GY");
insert into country(country_name, country_code) values ("HAITI", "HT");
insert into country(country_name, country_code) values ("HEARD ISLAND AND MCDONALD ISLANDS", "HM");
insert into country(country_name, country_code) values ("HOLY SEE (VATICAN CITY STATE)", "VA");
insert into country(country_name, country_code) values ("HONDURAS", "HN");
insert into country(country_name, country_code) values ("HONG KONG", "HK");
insert into country(country_name, country_code) values ("HUNGARY", "HU");
insert into country(country_name, country_code) values ("ICELAND", "IS");
insert into country(country_name, country_code) values ("INDIA", "IN");
insert into country(country_name, country_code) values ("INDONESIA", "ID");
insert into country(country_name, country_code) values ("IRAN, ISLAMIC REPUBLIC OF", "IR");
insert into country(country_name, country_code) values ("IRAQ", "IQ");
insert into country(country_name, country_code) values ("IRELAND", "IE");
insert into country(country_name, country_code) values ("ISRAEL", "IL");
insert into country(country_name, country_code) values ("ITALY", "IT");
insert into country(country_name, country_code) values ("JAMAICA", "JM");
insert into country(country_name, country_code) values ("JAPAN", "JP");
insert into country(country_name, country_code) values ("JORDAN", "JO");
insert into country(country_name, country_code) values ("KAZAKSTAN", "KZ");
insert into country(country_name, country_code) values ("KENYA", "KE");
insert into country(country_name, country_code) values ("KIRIBATI", "KI");
insert into country(country_name, country_code) values ("KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", "KP");
insert into country(country_name, country_code) values ("KOREA, REPUBLIC OF", "KR");
insert into country(country_name, country_code) values ("KUWAIT", "KW");
insert into country(country_name, country_code) values ("KYRGYZSTAN", "KG");
insert into country(country_name, country_code) values ("LAO PEOPLE'S DEMOCRATIC REPUBLIC", "LA");
insert into country(country_name, country_code) values ("LATVIA", "LV");
insert into country(country_name, country_code) values ("LEBANON", "LB");
insert into country(country_name, country_code) values ("LESOTHO", "LS");
insert into country(country_name, country_code) values ("LIBERIA", "LR");
insert into country(country_name, country_code) values ("LIBYAN ARAB JAMAHIRIYA", "LY");
insert into country(country_name, country_code) values ("LIECHTENSTEIN", "LI");
insert into country(country_name, country_code) values ("LITHUANIA", "LT");
insert into country(country_name, country_code) values ("LUXEMBOURG", "LU");
insert into country(country_name, country_code) values ("MACAU", "MO");
insert into country(country_name, country_code) values ("MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", "MK");
insert into country(country_name, country_code) values ("MADAGASCAR", "MG");
insert into country(country_name, country_code) values ("MALAWI", "MW");
insert into country(country_name, country_code) values ("MALAYSIA", "MY");
insert into country(country_name, country_code) values ("MALDIVES", "MV");
insert into country(country_name, country_code) values ("MALI", "ML");
insert into country(country_name, country_code) values ("MALTA", "MT");
insert into country(country_name, country_code) values ("MARSHALL ISLANDS", "MH");
insert into country(country_name, country_code) values ("MARTINIQUE", "MQ");
insert into country(country_name, country_code) values ("MAURITANIA", "MR");
insert into country(country_name, country_code) values ("MAURITIUS", "MU");
insert into country(country_name, country_code) values ("MAYOTTE", "YT");
insert into country(country_name, country_code) values ("MEXICO", "MX");
insert into country(country_name, country_code) values ("MICRONESIA, FEDERATED STATES OF", "FM");
insert into country(country_name, country_code) values ("MOLDOVA, REPUBLIC OF", "MD");
insert into country(country_name, country_code) values ("MONACO", "MC");
insert into country(country_name, country_code) values ("MONGOLIA", "MN");
insert into country(country_name, country_code) values ("MONTSERRAT", "MS");
insert into country(country_name, country_code) values ("MOROCCO", "MA");
insert into country(country_name, country_code) values ("MOZAMBIQUE", "MZ");
insert into country(country_name, country_code) values ("MYANMAR", "MM");
insert into country(country_name, country_code) values ("NAMIBIA", "NA");
insert into country(country_name, country_code) values ("NAURU", "NR");
insert into country(country_name, country_code) values ("NEPAL", "NP");
insert into country(country_name, country_code) values ("NETHERLANDS", "NL");
insert into country(country_name, country_code) values ("NETHERLANDS ANTILLES", "AN");
insert into country(country_name, country_code) values ("NEW CALEDONIA", "NC");
insert into country(country_name, country_code) values ("NEW ZEALAND", "NZ");
insert into country(country_name, country_code) values ("NICARAGUA", "NI");
insert into country(country_name, country_code) values ("NIGER", "NE");
insert into country(country_name, country_code) values ("NIGERIA", "NG");
insert into country(country_name, country_code) values ("NIUE", "NU");
insert into country(country_name, country_code) values ("NORFOLK ISLAND", "NF");
insert into country(country_name, country_code) values ("NORTHERN MARIANA ISLANDS", "MP");
insert into country(country_name, country_code) values ("NORWAY", "NO");
insert into country(country_name, country_code) values ("OMAN", "OM");
insert into country(country_name, country_code) values ("PAKISTAN", "PK");
insert into country(country_name, country_code) values ("PALAU", "PW");
insert into country(country_name, country_code) values ("PALESTINIAN TERRITORY, OCCUPIED", "PS");
insert into country(country_name, country_code) values ("PANAMA", "PA");
insert into country(country_name, country_code) values ("PAPUA NEW GUINEA", "PG");
insert into country(country_name, country_code) values ("PARAGUAY", "PY");
insert into country(country_name, country_code) values ("PERU", "PE");
insert into country(country_name, country_code) values ("PHILIPPINES", "PH");
insert into country(country_name, country_code) values ("PITCAIRN", "PN");
insert into country(country_name, country_code) values ("POLAND", "PL");
insert into country(country_name, country_code) values ("PORTUGAL", "PT");
insert into country(country_name, country_code) values ("PUERTO RICO", "PR");
insert into country(country_name, country_code) values ("QATAR", "QA");
insert into country(country_name, country_code) values ("R¨¦UNION", "RE");
insert into country(country_name, country_code) values ("ROMANIA", "RO");
insert into country(country_name, country_code) values ("RUSSIAN FEDERATION", "RU");
insert into country(country_name, country_code) values ("RWANDA", "RW");
insert into country(country_name, country_code) values ("SAINT HELENA", "SH");
insert into country(country_name, country_code) values ("SAINT KITTS AND NEVIS", "KN");
insert into country(country_name, country_code) values ("SAINT LUCIA", "LC");
insert into country(country_name, country_code) values ("SAINT PIERRE AND MIQUELON", "PM");
insert into country(country_name, country_code) values ("SAINT VINCENT AND THE GRENADINES", "VC");
insert into country(country_name, country_code) values ("SAMOA", "WS");
insert into country(country_name, country_code) values ("SAN MARINO", "SM");
insert into country(country_name, country_code) values ("SAO TOME AND PRINCIPE", "ST");
insert into country(country_name, country_code) values ("SAUDI ARABIA", "SA");
insert into country(country_name, country_code) values ("SENEGAL", "SN");
insert into country(country_name, country_code) values ("SEYCHELLES", "SC");
insert into country(country_name, country_code) values ("SIERRA LEONE", "SL");
insert into country(country_name, country_code) values ("SINGAPORE", "SG");
insert into country(country_name, country_code) values ("SLOVAKIA", "SK");
insert into country(country_name, country_code) values ("SLOVENIA", "SI");
insert into country(country_name, country_code) values ("SOLOMON ISLANDS", "SB");
insert into country(country_name, country_code) values ("SOMALIA", "SO");
insert into country(country_name, country_code) values ("SOUTH AFRICA", "ZA");
insert into country(country_name, country_code) values ("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "GS");
insert into country(country_name, country_code) values ("SPAIN", "ES");
insert into country(country_name, country_code) values ("SRI LANKA", "LK");
insert into country(country_name, country_code) values ("SUDAN", "SD");
insert into country(country_name, country_code) values ("SURINAME", "SR");
insert into country(country_name, country_code) values ("SVALBARD AND JAN MAYEN", "SJ");
insert into country(country_name, country_code) values ("SWAZILAND", "SZ");
insert into country(country_name, country_code) values ("SWEDEN", "SE");
insert into country(country_name, country_code) values ("SWITZERLAND", "CH");
insert into country(country_name, country_code) values ("SYRIAN ARAB REPUBLIC", "SY");
insert into country(country_name, country_code) values ("CHINAESE TAIBEI", "TW");
insert into country(country_name, country_code) values ("TAJIKISTAN", "TJ");
insert into country(country_name, country_code) values ("TANZANIA, UNITED REPUBLIC OF", "TZ");
insert into country(country_name, country_code) values ("THAILAND", "TH");
insert into country(country_name, country_code) values ("TOGO", "TG");
insert into country(country_name, country_code) values ("TOKELAU", "TK");
insert into country(country_name, country_code) values ("TONGA", "TO");
insert into country(country_name, country_code) values ("TRINIDAD AND TOBAGO", "TT");
insert into country(country_name, country_code) values ("TUNISIA", "TN");
insert into country(country_name, country_code) values ("TURKEY", "TR");
insert into country(country_name, country_code) values ("TURKMENISTAN", "TM");
insert into country(country_name, country_code) values ("TURKS AND CAICOS ISLANDS", "TC");
insert into country(country_name, country_code) values ("TUVALU", "TV");
insert into country(country_name, country_code) values ("UGANDA", "UG");
insert into country(country_name, country_code) values ("UKRAINE", "UA");
insert into country(country_name, country_code) values ("UNITED ARAB EMIRATES", "AE");
insert into country(country_name, country_code) values ("UNITED KINGDOM", "GB");
insert into country(country_name, country_code) values ("UNITED STATES", "US");
insert into country(country_name, country_code) values ("UNITED STATES MINOR OUTLYING ISLANDS", "UM");
insert into country(country_name, country_code) values ("URUGUAY", "UY");
insert into country(country_name, country_code) values ("UZBEKISTAN", "UZ");
insert into country(country_name, country_code) values ("VANUATU", "VU");
insert into country(country_name, country_code) values ("VENEZUELA", "VE");
insert into country(country_name, country_code) values ("VIET NAM", "VN");
insert into country(country_name, country_code) values ("VIRGIN ISLANDS, BRITISH", "VG");
insert into country(country_name, country_code) values ("VIRGIN ISLANDS, U.S.", "VI");
insert into country(country_name, country_code) values ("WALLIS AND FUTUNA", "WF");
insert into country(country_name, country_code) values ("WESTERN SAHARA", "EH");
insert into country(country_name, country_code) values ("YEMEN", "YE");
insert into country(country_name, country_code) values ("YUGOSLAVIA", "YU");
insert into country(country_name, country_code) values ("ZAMBIA", "ZM");
insert into country(country_name, country_code) values ("ZIMBABWE", "ZW");
